/* Generated by tools/voice/cut-recordings.py from the delivered recordings
   (assets/audio/source/story-*.mp3, docs/voice/cue-map.json). One file holds every
   part; `offset` is where a part starts in it, `duration` how long it is, and word
   starts are seconds from the start of the part. The player picks .ogg or .mp3. */
window.STORY_VOICE = {
  "src": "assets/audio/story/story-voice",
  "parts": {
    "scene-1/1": {
      "speaker": "narrator",
      "text": "Long ago,",
      "duration": 1.01,
      "words": [
        {
          "text": "Long",
          "start": 0.05
        },
        {
          "text": "ago,",
          "start": 0.32
        }
      ],
      "source": "recorded take: story-narrator.mp3, 0.00-1.01 s",
      "offset": 0.35
    },
    "scene-1/2": {
      "speaker": "narrator",
      "text": "Momo the mammoth and Popo the polar bear",
      "duration": 3.01,
      "words": [
        {
          "text": "Momo",
          "start": 0.06
        },
        {
          "text": "the",
          "start": 0.64
        },
        {
          "text": "mammoth",
          "start": 0.76
        },
        {
          "text": "and",
          "start": 1.43
        },
        {
          "text": "Popo",
          "start": 1.62
        },
        {
          "text": "the",
          "start": 2.1
        },
        {
          "text": "polar",
          "start": 2.26
        },
        {
          "text": "bear",
          "start": 2.56
        }
      ],
      "source": "recorded take: story-narrator.mp3, 1.18-4.19 s",
      "offset": 1.71
    },
    "scene-1/3": {
      "speaker": "narrator",
      "text": "were best friends.",
      "duration": 1.48,
      "words": [
        {
          "text": "were",
          "start": 0.06
        },
        {
          "text": "best",
          "start": 0.26
        },
        {
          "text": "friends.",
          "start": 0.72
        }
      ],
      "source": "recorded take: story-narrator.mp3, 4.24-5.72 s",
      "offset": 5.0699
    },
    "scene-2/1": {
      "speaker": "narrator",
      "text": "One day,",
      "duration": 0.79,
      "words": [
        {
          "text": "One",
          "start": 0.06
        },
        {
          "text": "day,",
          "start": 0.29
        }
      ],
      "source": "recorded take: story-narrator.mp3, 6.03-6.82 s",
      "offset": 6.8999
    },
    "scene-2/2": {
      "speaker": "narrator",
      "text": "Popo spotted something shiny",
      "duration": 1.85,
      "words": [
        {
          "text": "Popo",
          "start": 0.06
        },
        {
          "text": "spotted",
          "start": 0.5
        },
        {
          "text": "something",
          "start": 0.84
        },
        {
          "text": "shiny",
          "start": 1.22
        }
      ],
      "source": "recorded take: story-narrator.mp3, 6.98-8.83 s",
      "offset": 8.0399
    },
    "scene-2/3": {
      "speaker": "narrator",
      "text": "beneath the ice.",
      "duration": 0.984,
      "words": [
        {
          "text": "beneath",
          "start": 0.0
        },
        {
          "text": "the",
          "start": 0.21
        },
        {
          "text": "ice.",
          "start": 0.51
        }
      ],
      "source": "recorded take: story-narrator.mp3, 8.83-9.81 s",
      "offset": 10.2399
    },
    "scene-3/1": {
      "speaker": "polo",
      "text": "Momo, look!",
      "duration": 0.99,
      "words": [
        {
          "text": "Momo,",
          "start": 0.06
        },
        {
          "text": "look!",
          "start": 0.53
        }
      ],
      "source": "recorded take: story-popo.mp3, 0.03-1.02 s",
      "offset": 11.5739
    },
    "scene-3/2": {
      "speaker": "polo",
      "text": "Something is buried here!",
      "duration": 1.56,
      "words": [
        {
          "text": "Something",
          "start": 0.06
        },
        {
          "text": "is",
          "start": 0.45
        },
        {
          "text": "buried",
          "start": 0.69
        },
        {
          "text": "here!",
          "start": 1.05
        }
      ],
      "source": "recorded take: story-popo.mp3, 1.17-2.73 s",
      "offset": 12.9139
    },
    "scene-4/1": {
      "speaker": "momo",
      "text": "Let us pull it out!",
      "duration": 1.2,
      "words": [
        {
          "text": "Let",
          "start": 0.06
        },
        {
          "text": "us",
          "start": 0.26
        },
        {
          "text": "pull",
          "start": 0.42
        },
        {
          "text": "it",
          "start": 0.66
        },
        {
          "text": "out!",
          "start": 0.8
        }
      ],
      "source": "recorded take: story-momo.mp3, 0.02-1.22 s",
      "offset": 23.3338
    },
    "scene-5/1": {
      "speaker": "polo",
      "text": "Almost there!",
      "duration": 1.29,
      "words": [
        {
          "text": "Almost",
          "start": 0.06
        },
        {
          "text": "there!",
          "start": 0.6
        }
      ],
      "source": "recorded take: story-popo.mp3, 3.32-4.61 s",
      "offset": 14.8239
    },
    "scene-5/2": {
      "speaker": "polo",
      "text": "One more pull!",
      "duration": 1.36,
      "words": [
        {
          "text": "One",
          "start": 0.06
        },
        {
          "text": "more",
          "start": 0.41
        },
        {
          "text": "pull!",
          "start": 0.84
        }
      ],
      "source": "recorded take: story-popo.mp3, 5.03-6.39 s",
      "offset": 16.4639
    },
    "scene-6/1": {
      "speaker": "momo",
      "text": "Uh-oh...",
      "duration": 1.0,
      "words": [
        {
          "text": "Uh-oh...",
          "start": 0.06
        }
      ],
      "source": "recorded take: story-momo.mp3, 2.60-3.60 s",
      "offset": 24.8837
    },
    "scene-7/1": {
      "speaker": "polo",
      "text": "Run!",
      "duration": 0.76,
      "words": [
        {
          "text": "Run!",
          "start": 0.06
        }
      ],
      "source": "recorded take: story-popo.mp3, 7.00-7.76 s",
      "offset": 18.1738
    },
    "scene-8/1": {
      "speaker": "momo",
      "text": "Popo!",
      "duration": 0.801,
      "words": [
        {
          "text": "Popo!",
          "start": 0.06
        }
      ],
      "source": "recorded take: story-momo.mp3, 4.17-4.97 s",
      "offset": 26.2337
    },
    "scene-9/1": {
      "speaker": "polo",
      "text": "Momo, keep going!",
      "duration": 1.58,
      "words": [
        {
          "text": "Momo,",
          "start": 0.06
        },
        {
          "text": "keep",
          "start": 0.72
        },
        {
          "text": "going!",
          "start": 0.87
        }
      ],
      "source": "recorded take: story-popo.mp3, 7.95-9.53 s",
      "offset": 19.2838
    },
    "scene-9/2": {
      "speaker": "polo",
      "text": "I will find another way!",
      "duration": 1.77,
      "words": [
        {
          "text": "I",
          "start": 0.06
        },
        {
          "text": "will",
          "start": 0.21
        },
        {
          "text": "find",
          "start": 0.39
        },
        {
          "text": "another",
          "start": 0.83
        },
        {
          "text": "way!",
          "start": 1.35
        }
      ],
      "source": "recorded take: story-popo.mp3, 9.73-11.50 s",
      "offset": 21.2138
    }
  }
};
