/* Generated by tools/story/build-story-voice.py. One file holds every take;
   `offset` is where a take starts in it, `duration` how long it is, and word
   starts are seconds from the start of the take. The player picks .ogg or .mp3. */
window.STORY_VOICE = {
  "src": "assets/audio/story/story-voice",
  "parts": {
    "scene-1/1": {
      "speaker": "narrator",
      "text": "Long ago,",
      "duration": 0.88,
      "words": [
        {
          "text": "Long",
          "start": 0.01
        },
        {
          "text": "ago,",
          "start": 0.296
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 0.35
    },
    "scene-1/2": {
      "speaker": "narrator",
      "text": "Momo the mammoth and Polo the polar bear",
      "duration": 2.5,
      "words": [
        {
          "text": "Momo",
          "start": 0.01
        },
        {
          "text": "the",
          "start": 0.359
        },
        {
          "text": "mammoth",
          "start": 0.543
        },
        {
          "text": "and",
          "start": 0.92
        },
        {
          "text": "Polo",
          "start": 1.137
        },
        {
          "text": "the",
          "start": 1.55
        },
        {
          "text": "polar",
          "start": 1.73
        },
        {
          "text": "bear",
          "start": 2.178
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 1.58
    },
    "scene-1/3": {
      "speaker": "narrator",
      "text": "were best friends.",
      "duration": 1.24,
      "words": [
        {
          "text": "were",
          "start": 0.01
        },
        {
          "text": "best",
          "start": 0.376
        },
        {
          "text": "friends.",
          "start": 0.741
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 4.43
    },
    "scene-2/1": {
      "speaker": "narrator",
      "text": "One day,",
      "duration": 0.8,
      "words": [
        {
          "text": "One",
          "start": 0.01
        },
        {
          "text": "day,",
          "start": 0.365
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 6.02
    },
    "scene-2/2": {
      "speaker": "narrator",
      "text": "Polo spotted something shiny",
      "duration": 2.12,
      "words": [
        {
          "text": "Polo",
          "start": 0.0
        },
        {
          "text": "spotted",
          "start": 0.54
        },
        {
          "text": "something",
          "start": 0.979
        },
        {
          "text": "shiny",
          "start": 1.622
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 7.17
    },
    "scene-2/3": {
      "speaker": "narrator",
      "text": "beneath the ice.",
      "duration": 1.18,
      "words": [
        {
          "text": "beneath",
          "start": 0.02
        },
        {
          "text": "the",
          "start": 0.49
        },
        {
          "text": "ice.",
          "start": 0.795
        }
      ],
      "source": "macOS say -v Tara, pitch +0 cents, pace x0.84 (placeholder take)",
      "offset": 9.64
    },
    "scene-3/1": {
      "speaker": "polo",
      "text": "Momo, look!",
      "duration": 0.86,
      "words": [
        {
          "text": "Momo,",
          "start": 0.02
        },
        {
          "text": "look!",
          "start": 0.68
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.90 (placeholder take)",
      "offset": 11.17
    },
    "scene-3/2": {
      "speaker": "polo",
      "text": "Something is buried here!",
      "duration": 1.54,
      "words": [
        {
          "text": "Something",
          "start": 0.03
        },
        {
          "text": "is",
          "start": 0.71
        },
        {
          "text": "buried",
          "start": 0.888
        },
        {
          "text": "here!",
          "start": 1.263
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.90 (placeholder take)",
      "offset": 12.38
    },
    "scene-4/1": {
      "speaker": "momo",
      "text": "Let us pull it out!",
      "duration": 1.26,
      "words": [
        {
          "text": "Let",
          "start": 0.01
        },
        {
          "text": "us",
          "start": 0.313
        },
        {
          "text": "pull",
          "start": 0.6
        },
        {
          "text": "it",
          "start": 0.803
        },
        {
          "text": "out!",
          "start": 0.987
        }
      ],
      "source": "macOS say -v Aman, pitch +550 cents, pace x0.80 (placeholder take)",
      "offset": 14.27
    },
    "scene-5/1": {
      "speaker": "polo",
      "text": "Almost there!",
      "duration": 0.97,
      "words": [
        {
          "text": "Almost",
          "start": 0.0
        },
        {
          "text": "there!",
          "start": 0.57
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.90 (placeholder take)",
      "offset": 15.88
    },
    "scene-5/2": {
      "speaker": "polo",
      "text": "One more pull!",
      "duration": 0.92,
      "words": [
        {
          "text": "One",
          "start": 0.01
        },
        {
          "text": "more",
          "start": 0.268
        },
        {
          "text": "pull!",
          "start": 0.54
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.90 (placeholder take)",
      "offset": 17.2
    },
    "scene-6/1": {
      "speaker": "momo",
      "text": "Uh-oh...",
      "duration": 0.66,
      "words": [
        {
          "text": "Uh-oh...",
          "start": 0.0
        }
      ],
      "source": "macOS say -v Aman, pitch +550 cents, pace x0.62 (placeholder take)",
      "offset": 18.47
    },
    "scene-7/1": {
      "speaker": "polo",
      "text": "Run!",
      "duration": 0.44,
      "words": [
        {
          "text": "Run!",
          "start": 0.0
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x1.00 (placeholder take)",
      "offset": 19.48
    },
    "scene-8/1": {
      "speaker": "momo",
      "text": "Polo!",
      "duration": 0.63,
      "words": [
        {
          "text": "Polo!",
          "start": 0.0
        }
      ],
      "source": "macOS say -v Aman, pitch +550 cents, pace x0.68 (placeholder take)",
      "offset": 20.27
    },
    "scene-9/1": {
      "speaker": "polo",
      "text": "Momo, keep going!",
      "duration": 1.26,
      "words": [
        {
          "text": "Momo,",
          "start": 0.01
        },
        {
          "text": "keep",
          "start": 0.72
        },
        {
          "text": "going!",
          "start": 0.945
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.86 (placeholder take)",
      "offset": 21.25
    },
    "scene-9/2": {
      "speaker": "polo",
      "text": "I will find another way!",
      "duration": 1.63,
      "words": [
        {
          "text": "I",
          "start": 0.0
        },
        {
          "text": "will",
          "start": 0.217
        },
        {
          "text": "find",
          "start": 0.47
        },
        {
          "text": "another",
          "start": 0.699
        },
        {
          "text": "way!",
          "start": 1.332
        }
      ],
      "source": "macOS say -v Tara, pitch +750 cents, pace x0.86 (placeholder take)",
      "offset": 22.86
    }
  }
};
