/* Generated by tools/voice/build-hindi-voice.py from the delivered Hindi takes
   (assets/audio/source/hi/, docs/voice/hi/cue-map.json). Loaded by src/i18n/i18n.js for ?lan=hi
   on a page that asks for its voice (index.html). A row is found by its English `text`, as the
   English catalogue's (src/lesson/recordings.js) are; `shown` is the Hindi on screen, `spoken`
   when each of its words starts, and `words` each English word with the moment its cue fires in
   this take (seconds from the start of the file, not in order: Hindi puts its words in its own
   order). See PolygonRecordedVoice in src/lesson/recorded-player.js. */
(window.POLYGON_VOICES = window.POLYGON_VOICES || {}).hi = [
 {
  "text": "Momo needs your help.",
  "shown": "मोमो को आपकी मदद चाहिए।",
  "src": "assets/audio/lesson/hi/92_Momo_needs_your_help.mp3",
  "duration": 2.26,
  "spoken": [
   {
    "word": "मोमो",
    "start": 0.25
   },
   {
    "word": "को",
    "start": 0.67
   },
   {
    "word": "आपकी",
    "start": 0.87
   },
   {
    "word": "मदद",
    "start": 1.17
   },
   {
    "word": "चाहिए।",
    "start": 1.51
   }
  ],
  "words": [
   {
    "word": "Momo",
    "start": 0.25
   },
   {
    "word": "needs",
    "start": 0.67
   },
   {
    "word": "your",
    "start": 0.87
   },
   {
    "word": "help.",
    "start": 1.17
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/47.flac (swifteeNeedsHelp), 0.05-2.31 s"
 },
 {
  "text": "But to help Momo, you need to learn about polygons.",
  "shown": "लेकिन मोमो की मदद करने के लिए आपको बहुभुज के बारे में सीखना होगा।",
  "src": "assets/audio/lesson/hi/91_But_to_help_Momo_you_need_to_learn_about_polygons.mp3",
  "duration": 5.07,
  "spoken": [
   {
    "word": "लेकिन",
    "start": 0.25
   },
   {
    "word": "मोमो",
    "start": 0.75
   },
   {
    "word": "की",
    "start": 1.17
   },
   {
    "word": "मदद",
    "start": 1.33
   },
   {
    "word": "करने",
    "start": 1.65
   },
   {
    "word": "के",
    "start": 1.97
   },
   {
    "word": "लिए",
    "start": 2.15
   },
   {
    "word": "आपको",
    "start": 2.58
   },
   {
    "word": "बहुभुज",
    "start": 2.97
   },
   {
    "word": "के",
    "start": 3.61
   },
   {
    "word": "बारे",
    "start": 3.79
   },
   {
    "word": "में",
    "start": 4.03
   },
   {
    "word": "सीखना",
    "start": 4.19
   },
   {
    "word": "होगा।",
    "start": 4.53
   }
  ],
  "words": [
   {
    "word": "But",
    "start": 0.25
   },
   {
    "word": "to",
    "start": 0.75
   },
   {
    "word": "help",
    "start": 1.17
   },
   {
    "word": "Momo,",
    "start": 1.65
   },
   {
    "word": "you",
    "start": 1.97
   },
   {
    "word": "need",
    "start": 2.58
   },
   {
    "word": "to",
    "start": 2.97
   },
   {
    "word": "learn",
    "start": 3.61
   },
   {
    "word": "about",
    "start": 4.03
   },
   {
    "word": "polygons.",
    "start": 2.97
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/48.flac (swifteeLearnFirst), 0.03-5.10 s"
 },
 {
  "text": "Now let's help Momo.",
  "shown": "चलिए, अब मोमो की मदद करते हैं।",
  "src": "assets/audio/lesson/hi/90_Now_lets_help_Momo.mp3",
  "duration": 2.69,
  "spoken": [
   {
    "word": "चलिए,",
    "start": 0.25
   },
   {
    "word": "अब",
    "start": 0.98
   },
   {
    "word": "मोमो",
    "start": 1.18
   },
   {
    "word": "की",
    "start": 1.5
   },
   {
    "word": "मदद",
    "start": 1.66
   },
   {
    "word": "करते",
    "start": 1.94
   },
   {
    "word": "हैं।",
    "start": 2.28
   }
  ],
  "words": [
   {
    "word": "Now",
    "start": 0.25
   },
   {
    "word": "let's",
    "start": 0.98
   },
   {
    "word": "help",
    "start": 1.5
   },
   {
    "word": "Momo.",
    "start": 1.94
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/49.flac (swifteeLetsHelp), 0.04-2.73 s"
 },
 {
  "text": "Look! A point.",
  "shown": "देखिए! एक बिंदु।",
  "src": "assets/audio/lesson/hi/01_Look_A_point.mp3",
  "duration": 2.33,
  "spoken": [
   {
    "word": "देखिए!",
    "start": 0.25
   },
   {
    "word": "एक",
    "start": 1.37
   },
   {
    "word": "बिंदु।",
    "start": 1.62
   }
  ],
  "words": [
   {
    "word": "Look!",
    "start": 0.25
   },
   {
    "word": "A",
    "start": 1.37
   },
   {
    "word": "point.",
    "start": 1.62
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/50.flac (s01Point), 0.04-2.37 s"
 },
 {
  "text": "Woah! It drew a shape.",
  "shown": "वाह! इसने एक आकृति बना दी।",
  "src": "assets/audio/lesson/hi/02_Woah_It_drew_a_shape.mp3",
  "duration": 3.21,
  "spoken": [
   {
    "word": "वाह!",
    "start": 0.25
   },
   {
    "word": "इसने",
    "start": 1.21
   },
   {
    "word": "एक",
    "start": 1.62
   },
   {
    "word": "आकृति",
    "start": 1.76
   },
   {
    "word": "बना",
    "start": 2.36
   },
   {
    "word": "दी।",
    "start": 2.68
   }
  ],
  "words": [
   {
    "word": "Woah!",
    "start": 0.25
   },
   {
    "word": "It",
    "start": 1.21
   },
   {
    "word": "drew",
    "start": 1.62
   },
   {
    "word": "a",
    "start": 1.76
   },
   {
    "word": "shape.",
    "start": 1.76
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/51.flac (s02DrewShape), 0.04-3.25 s"
 },
 {
  "text": "Let's look at this shape closely.",
  "shown": "आइए, इस आकृति को ध्यान से देखें।",
  "src": "assets/audio/lesson/hi/03_Lets_look_at_this_shape_closely.mp3",
  "duration": 2.98,
  "spoken": [
   {
    "word": "आइए,",
    "start": 0.25
   },
   {
    "word": "इस",
    "start": 1.08
   },
   {
    "word": "आकृति",
    "start": 1.31
   },
   {
    "word": "को",
    "start": 1.73
   },
   {
    "word": "ध्यान",
    "start": 1.91
   },
   {
    "word": "से",
    "start": 2.21
   },
   {
    "word": "देखें।",
    "start": 2.39
   }
  ],
  "words": [
   {
    "word": "Let's",
    "start": 0.25
   },
   {
    "word": "look",
    "start": 2.39
   },
   {
    "word": "at",
    "start": 1.31
   },
   {
    "word": "this",
    "start": 1.73
   },
   {
    "word": "shape",
    "start": 1.31
   },
   {
    "word": "closely.",
    "start": 2.21
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/52.flac (s03LookClosely), 0.05-3.03 s"
 },
 {
  "text": "There are no gaps in its boundary.",
  "shown": "इसकी सीमा में कोई खाली जगह नहीं है।",
  "src": "assets/audio/lesson/hi/04_There_are_no_gaps_in_its_boundary.mp3",
  "duration": 2.89,
  "spoken": [
   {
    "word": "इसकी",
    "start": 0.25
   },
   {
    "word": "सीमा",
    "start": 0.58
   },
   {
    "word": "में",
    "start": 0.98
   },
   {
    "word": "कोई",
    "start": 1.26
   },
   {
    "word": "खाली",
    "start": 1.54
   },
   {
    "word": "जगह",
    "start": 1.92
   },
   {
    "word": "नहीं",
    "start": 2.2
   },
   {
    "word": "है।",
    "start": 2.5
   }
  ],
  "words": [
   {
    "word": "There",
    "start": 0.25
   },
   {
    "word": "are",
    "start": 0.58
   },
   {
    "word": "no",
    "start": 0.98
   },
   {
    "word": "gaps",
    "start": 1.54
   },
   {
    "word": "in",
    "start": 1.54
   },
   {
    "word": "its",
    "start": 1.92
   },
   {
    "word": "boundary.",
    "start": 0.58
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/53.flac (s04NoGaps), 0.02-2.91 s"
 },
 {
  "text": "Is it open or closed?",
  "shown": "यह खुली है या बंद?",
  "src": "assets/audio/lesson/hi/05_Is_it_open_or_closed.mp3",
  "duration": 2.23,
  "spoken": [
   {
    "word": "यह",
    "start": 0.25
   },
   {
    "word": "खुली",
    "start": 0.64
   },
   {
    "word": "है",
    "start": 1.06
   },
   {
    "word": "या",
    "start": 1.36
   },
   {
    "word": "बंद?",
    "start": 1.58
   }
  ],
  "words": [
   {
    "word": "Is",
    "start": 0.25
   },
   {
    "word": "it",
    "start": 0.64
   },
   {
    "word": "open",
    "start": 0.64
   },
   {
    "word": "or",
    "start": 1.36
   },
   {
    "word": "closed?",
    "start": 1.58
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/54.flac (s05OpenOrClosed), 0.00-2.23 s"
 },
 {
  "text": "Is this shape open or closed?",
  "shown": "यह आकृति खुली है या बंद?",
  "src": "assets/audio/lesson/hi/06_Is_this_shape_open_or_closed.mp3",
  "duration": 2.97,
  "spoken": [
   {
    "word": "यह",
    "start": 0.25
   },
   {
    "word": "आकृति",
    "start": 0.54
   },
   {
    "word": "खुली",
    "start": 1.32
   },
   {
    "word": "है",
    "start": 1.72
   },
   {
    "word": "या",
    "start": 2.12
   },
   {
    "word": "बंद?",
    "start": 2.36
   }
  ],
  "words": [
   {
    "word": "Is",
    "start": 0.25
   },
   {
    "word": "this",
    "start": 0.54
   },
   {
    "word": "shape",
    "start": 0.54
   },
   {
    "word": "open",
    "start": 1.32
   },
   {
    "word": "or",
    "start": 2.12
   },
   {
    "word": "closed?",
    "start": 2.36
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/55.flac (s06ThisShapeOpenOrClosed), 0.04-3.01 s"
 },
 {
  "text": "What about this one?",
  "shown": "इसके बारे में क्या?",
  "src": "assets/audio/lesson/hi/07_What_about_this_one.mp3",
  "duration": 1.4,
  "spoken": [
   {
    "word": "इसके",
    "start": 0.25
   },
   {
    "word": "बारे",
    "start": 0.58
   },
   {
    "word": "में",
    "start": 0.84
   },
   {
    "word": "क्या?",
    "start": 1.0
   }
  ],
  "words": [
   {
    "word": "What",
    "start": 0.25
   },
   {
    "word": "about",
    "start": 0.58
   },
   {
    "word": "this",
    "start": 0.84
   },
   {
    "word": "one?",
    "start": 1.0
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/56.flac (s07WhatAboutThis), 0.10-1.50 s"
 },
 {
  "text": "And this?",
  "shown": "और यह?",
  "src": "assets/audio/lesson/hi/08_And_this.mp3",
  "duration": 1.1,
  "spoken": [
   {
    "word": "और",
    "start": 0.25
   },
   {
    "word": "यह?",
    "start": 0.55
   }
  ],
  "words": [
   {
    "word": "And",
    "start": 0.25
   },
   {
    "word": "this?",
    "start": 0.55
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/57.flac (s08AndThis), 0.03-1.13 s"
 },
 {
  "text": "How about this one?",
  "shown": "यह वाली कैसी है?",
  "src": "assets/audio/lesson/hi/09_How_about_this_one.mp3",
  "duration": 1.7,
  "spoken": [
   {
    "word": "यह",
    "start": 0.25
   },
   {
    "word": "वाली",
    "start": 0.58
   },
   {
    "word": "कैसी",
    "start": 0.88
   },
   {
    "word": "है?",
    "start": 1.28
   }
  ],
  "words": [
   {
    "word": "How",
    "start": 0.25
   },
   {
    "word": "about",
    "start": 0.58
   },
   {
    "word": "this",
    "start": 0.88
   },
   {
    "word": "one?",
    "start": 1.28
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/58.flac (s09HowAboutThis), 0.02-1.72 s"
 },
 {
  "text": "No gaps in its boundary. This shape is closed.",
  "shown": "इसकी सीमा में कोई खाली जगह नहीं। यह आकृति बंद है।",
  "src": "assets/audio/lesson/hi/48_No_gaps_in_its_boundary_This_shape_is_closed.mp3",
  "duration": 4.8,
  "spoken": [
   {
    "word": "इसकी",
    "start": 0.25
   },
   {
    "word": "सीमा",
    "start": 0.62
   },
   {
    "word": "में",
    "start": 1.1
   },
   {
    "word": "कोई",
    "start": 1.47
   },
   {
    "word": "खाली",
    "start": 1.72
   },
   {
    "word": "जगह",
    "start": 2.14
   },
   {
    "word": "नहीं।",
    "start": 2.44
   },
   {
    "word": "यह",
    "start": 3.14
   },
   {
    "word": "आकृति",
    "start": 3.38
   },
   {
    "word": "बंद",
    "start": 4.07
   },
   {
    "word": "है।",
    "start": 4.44
   }
  ],
  "words": [
   {
    "word": "No",
    "start": 0.25
   },
   {
    "word": "gaps",
    "start": 1.72
   },
   {
    "word": "in",
    "start": 1.1
   },
   {
    "word": "its",
    "start": 1.72
   },
   {
    "word": "boundary.",
    "start": 0.62
   },
   {
    "word": "This",
    "start": 3.14
   },
   {
    "word": "shape",
    "start": 3.38
   },
   {
    "word": "is",
    "start": 4.07
   },
   {
    "word": "closed.",
    "start": 4.07
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/59.flac (ocFbClosed), 0.02-4.82 s"
 },
 {
  "text": "There is a gap in its boundary. It is open.",
  "shown": "इसकी सीमा में खाली जगह है। यह खुली है।",
  "src": "assets/audio/lesson/hi/49_There_is_a_gap_in_its_boundary_It_is_open.mp3",
  "duration": 3.61,
  "spoken": [
   {
    "word": "इसकी",
    "start": 0.25
   },
   {
    "word": "सीमा",
    "start": 0.62
   },
   {
    "word": "में",
    "start": 1.04
   },
   {
    "word": "खाली",
    "start": 1.26
   },
   {
    "word": "जगह",
    "start": 1.68
   },
   {
    "word": "है।",
    "start": 1.98
   },
   {
    "word": "यह",
    "start": 2.59
   },
   {
    "word": "खुली",
    "start": 2.78
   },
   {
    "word": "है।",
    "start": 3.18
   }
  ],
  "words": [
   {
    "word": "There",
    "start": 0.25
   },
   {
    "word": "is",
    "start": 0.25
   },
   {
    "word": "a",
    "start": 0.62
   },
   {
    "word": "gap",
    "start": 1.26
   },
   {
    "word": "in",
    "start": 1.26
   },
   {
    "word": "its",
    "start": 1.68
   },
   {
    "word": "boundary.",
    "start": 0.62
   },
   {
    "word": "It",
    "start": 2.59
   },
   {
    "word": "is",
    "start": 2.78
   },
   {
    "word": "open.",
    "start": 2.78
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/60.flac (ocFbOpen), 0.02-3.63 s"
 },
 {
  "text": "Yes! It is closed.",
  "shown": "हाँ! यह बंद है।",
  "src": "assets/audio/lesson/hi/66_Yes_It_is_closed.mp3",
  "duration": 1.99,
  "spoken": [
   {
    "word": "हाँ!",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 0.93
   },
   {
    "word": "बंद",
    "start": 1.16
   },
   {
    "word": "है।",
    "start": 1.52
   }
  ],
  "words": [
   {
    "word": "Yes!",
    "start": 0.25
   },
   {
    "word": "It",
    "start": 0.93
   },
   {
    "word": "is",
    "start": 1.16
   },
   {
    "word": "closed.",
    "start": 1.16
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/61.flac (ocYesClosed), 0.00-1.99 s"
 },
 {
  "text": "Yes! It is open.",
  "shown": "हाँ! यह खुली है।",
  "src": "assets/audio/lesson/hi/67_Yes_It_is_open.mp3",
  "duration": 1.87,
  "spoken": [
   {
    "word": "हाँ!",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 0.84
   },
   {
    "word": "खुली",
    "start": 0.98
   },
   {
    "word": "है।",
    "start": 1.38
   }
  ],
  "words": [
   {
    "word": "Yes!",
    "start": 0.25
   },
   {
    "word": "It",
    "start": 0.84
   },
   {
    "word": "is",
    "start": 0.98
   },
   {
    "word": "open.",
    "start": 0.98
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/62.flac (ocYesOpen), 0.02-1.89 s"
 },
 {
  "text": "These two shapes are open...",
  "shown": "ये दो आकृतियाँ खुली हैं...",
  "src": "assets/audio/lesson/hi/10_These_two_shapes_are_open.mp3",
  "duration": 2.26,
  "spoken": [
   {
    "word": "ये",
    "start": 0.25
   },
   {
    "word": "दो",
    "start": 0.55
   },
   {
    "word": "आकृतियाँ",
    "start": 0.81
   },
   {
    "word": "खुली",
    "start": 1.53
   },
   {
    "word": "हैं...",
    "start": 1.81
   }
  ],
  "words": [
   {
    "word": "These",
    "start": 0.25
   },
   {
    "word": "two",
    "start": 0.55
   },
   {
    "word": "shapes",
    "start": 0.81
   },
   {
    "word": "are",
    "start": 1.53
   },
   {
    "word": "open...",
    "start": 1.53
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/63.flac (s10TwoOpen), 0.01-2.27 s"
 },
 {
  "text": "...and these two shapes are closed.",
  "shown": "...और ये दो आकृतियाँ बंद हैं।",
  "src": "assets/audio/lesson/hi/11_and_these_two_shapes_are_closed.mp3",
  "duration": 2.87,
  "spoken": [
   {
    "word": "...और",
    "start": 0.25
   },
   {
    "word": "ये",
    "start": 0.6
   },
   {
    "word": "दो",
    "start": 0.84
   },
   {
    "word": "आकृतियाँ",
    "start": 1.16
   },
   {
    "word": "बंद",
    "start": 2.04
   },
   {
    "word": "हैं।",
    "start": 2.44
   }
  ],
  "words": [
   {
    "word": "...and",
    "start": 0.25
   },
   {
    "word": "these",
    "start": 0.6
   },
   {
    "word": "two",
    "start": 0.84
   },
   {
    "word": "shapes",
    "start": 1.16
   },
   {
    "word": "are",
    "start": 2.04
   },
   {
    "word": "closed.",
    "start": 2.04
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/64.flac (s11TwoClosed), 0.02-2.89 s"
 },
 {
  "text": "Look! The boundaries of the shapes are different too.",
  "shown": "देखिए! आकृतियों की सीमाएँ भी अलग-अलग हैं।",
  "src": "assets/audio/lesson/hi/12_Look_The_boundaries_of_the_shapes_are_different_too.mp3",
  "duration": 3.53,
  "spoken": [
   {
    "word": "देखिए!",
    "start": 0.25
   },
   {
    "word": "आकृतियों",
    "start": 1.13
   },
   {
    "word": "की",
    "start": 1.76
   },
   {
    "word": "सीमाएँ",
    "start": 1.92
   },
   {
    "word": "भी",
    "start": 2.44
   },
   {
    "word": "अलग-अलग",
    "start": 2.62
   },
   {
    "word": "हैं।",
    "start": 3.16
   }
  ],
  "words": [
   {
    "word": "Look!",
    "start": 0.25
   },
   {
    "word": "The",
    "start": 1.13
   },
   {
    "word": "boundaries",
    "start": 1.92
   },
   {
    "word": "of",
    "start": 1.76
   },
   {
    "word": "the",
    "start": 1.92
   },
   {
    "word": "shapes",
    "start": 1.13
   },
   {
    "word": "are",
    "start": 2.44
   },
   {
    "word": "different",
    "start": 2.62
   },
   {
    "word": "too.",
    "start": 3.16
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/65.flac (s12BoundariesDifferent), 0.04-3.57 s"
 },
 {
  "text": "Some are straight and some are curved.",
  "shown": "कुछ सीधी हैं और कुछ वक्र।",
  "src": "assets/audio/lesson/hi/13_Some_are_straight_and_some_are_curved.mp3",
  "duration": 2.71,
  "spoken": [
   {
    "word": "कुछ",
    "start": 0.25
   },
   {
    "word": "सीधी",
    "start": 0.44
   },
   {
    "word": "हैं",
    "start": 0.94
   },
   {
    "word": "और",
    "start": 1.52
   },
   {
    "word": "कुछ",
    "start": 1.7
   },
   {
    "word": "वक्र।",
    "start": 1.94
   }
  ],
  "words": [
   {
    "word": "Some",
    "start": 0.25
   },
   {
    "word": "are",
    "start": 0.25
   },
   {
    "word": "straight",
    "start": 0.44
   },
   {
    "word": "and",
    "start": 0.94
   },
   {
    "word": "some",
    "start": 1.52
   },
   {
    "word": "are",
    "start": 1.7
   },
   {
    "word": "curved.",
    "start": 1.94
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/66.flac (s13StraightAndCurved), 0.02-2.73 s"
 },
 {
  "text": "Which boundaries are straight and which are curved?",
  "shown": "कौन-सी सीमाएँ सीधी हैं और कौन-सी वक्र?",
  "src": "assets/audio/lesson/hi/14_Which_boundaries_are_straight_and_which_are_curved.mp3",
  "duration": 3.58,
  "spoken": [
   {
    "word": "कौन-सी",
    "start": 0.25
   },
   {
    "word": "सीमाएँ",
    "start": 0.79
   },
   {
    "word": "सीधी",
    "start": 1.35
   },
   {
    "word": "हैं",
    "start": 1.71
   },
   {
    "word": "और",
    "start": 2.15
   },
   {
    "word": "कौन-सी",
    "start": 2.45
   },
   {
    "word": "वक्र?",
    "start": 2.89
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 0.25
   },
   {
    "word": "boundaries",
    "start": 0.79
   },
   {
    "word": "are",
    "start": 0.79
   },
   {
    "word": "straight",
    "start": 1.35
   },
   {
    "word": "and",
    "start": 1.71
   },
   {
    "word": "which",
    "start": 2.45
   },
   {
    "word": "are",
    "start": 2.45
   },
   {
    "word": "curved?",
    "start": 2.89
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/67.flac (s14WhichStraightCurved), 0.03-3.61 s"
 },
 {
  "text": "Is the boundary straight or curved?",
  "shown": "यह सीमा सीधी है या वक्र?",
  "src": "assets/audio/lesson/hi/88_Is_the_boundary_straight_or_curved.mp3",
  "duration": 2.91,
  "spoken": [
   {
    "word": "यह",
    "start": 0.25
   },
   {
    "word": "सीमा",
    "start": 0.56
   },
   {
    "word": "सीधी",
    "start": 1.02
   },
   {
    "word": "है",
    "start": 1.56
   },
   {
    "word": "या",
    "start": 2.06
   },
   {
    "word": "वक्र?",
    "start": 2.28
   }
  ],
  "words": [
   {
    "word": "Is",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.56
   },
   {
    "word": "boundary",
    "start": 0.56
   },
   {
    "word": "straight",
    "start": 1.02
   },
   {
    "word": "or",
    "start": 2.06
   },
   {
    "word": "curved?",
    "start": 2.28
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/68.flac (s14AskAgain), 0.02-2.93 s"
 },
 {
  "text": "Look! This boundary isn't curved. It is made of straight lines.",
  "shown": "देखिए! यह सीमा वक्र नहीं है। यह सीधी रेखाओं से बनी है।",
  "src": "assets/audio/lesson/hi/68_Look_This_boundary_isnt_curved_It_is_made_of_straight_lines.mp3",
  "duration": 5.35,
  "spoken": [
   {
    "word": "देखिए!",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 1.23
   },
   {
    "word": "सीमा",
    "start": 1.5
   },
   {
    "word": "वक्र",
    "start": 2.06
   },
   {
    "word": "नहीं",
    "start": 2.34
   },
   {
    "word": "है।",
    "start": 2.688
   },
   {
    "word": "यह",
    "start": 3.25
   },
   {
    "word": "सीधी",
    "start": 3.48
   },
   {
    "word": "रेखाओं",
    "start": 3.98
   },
   {
    "word": "से",
    "start": 4.5
   },
   {
    "word": "बनी",
    "start": 4.68
   },
   {
    "word": "है।",
    "start": 4.94
   }
  ],
  "words": [
   {
    "word": "Look!",
    "start": 0.25
   },
   {
    "word": "This",
    "start": 1.23
   },
   {
    "word": "boundary",
    "start": 1.5
   },
   {
    "word": "isn't",
    "start": 2.06
   },
   {
    "word": "curved.",
    "start": 2.06
   },
   {
    "word": "It",
    "start": 3.25
   },
   {
    "word": "is",
    "start": 3.48
   },
   {
    "word": "made",
    "start": 3.98
   },
   {
    "word": "of",
    "start": 4.5
   },
   {
    "word": "straight",
    "start": 3.48
   },
   {
    "word": "lines.",
    "start": 3.98
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/69.flac (s14NotCurved), 0.00-5.27 s"
 },
 {
  "text": "Look closely. This boundary bends smoothly. It is curved.",
  "shown": "ध्यान से देखिए। यह सीमा धीरे-धीरे मुड़ती है। यह वक्र है।",
  "src": "assets/audio/lesson/hi/69_Look_closely_This_boundary_bends_smoothly_It_is_curved.mp3",
  "duration": 6.08,
  "spoken": [
   {
    "word": "ध्यान",
    "start": 0.25
   },
   {
    "word": "से",
    "start": 0.71
   },
   {
    "word": "देखिए।",
    "start": 0.91
   },
   {
    "word": "यह",
    "start": 1.79
   },
   {
    "word": "सीमा",
    "start": 2.03
   },
   {
    "word": "धीरे-धीरे",
    "start": 2.47
   },
   {
    "word": "मुड़ती",
    "start": 3.43
   },
   {
    "word": "है।",
    "start": 3.81
   },
   {
    "word": "यह",
    "start": 4.57
   },
   {
    "word": "वक्र",
    "start": 5.2
   },
   {
    "word": "है।",
    "start": 5.65
   }
  ],
  "words": [
   {
    "word": "Look",
    "start": 0.91
   },
   {
    "word": "closely.",
    "start": 0.71
   },
   {
    "word": "This",
    "start": 1.79
   },
   {
    "word": "boundary",
    "start": 2.03
   },
   {
    "word": "bends",
    "start": 2.47
   },
   {
    "word": "smoothly.",
    "start": 3.43
   },
   {
    "word": "It",
    "start": 4.57
   },
   {
    "word": "is",
    "start": 5.2
   },
   {
    "word": "curved.",
    "start": 5.2
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/70.flac (s14IsCurved), 0.03-6.11 s"
 },
 {
  "text": "You got it! These boundaries are straight, while these are curved.",
  "shown": "बिल्कुल सही! ये सीमाएँ सीधी हैं, जबकि ये वक्र हैं।",
  "src": "assets/audio/lesson/hi/15_You_got_it_These_boundaries_are_straight_while_these_are_curve.mp3",
  "duration": 4.64,
  "spoken": [
   {
    "word": "बिल्कुल",
    "start": 0.25
   },
   {
    "word": "सही!",
    "start": 0.76
   },
   {
    "word": "ये",
    "start": 1.47
   },
   {
    "word": "सीमाएँ",
    "start": 1.68
   },
   {
    "word": "सीधी",
    "start": 2.2
   },
   {
    "word": "हैं,",
    "start": 2.68
   },
   {
    "word": "जबकि",
    "start": 3.17
   },
   {
    "word": "ये",
    "start": 3.58
   },
   {
    "word": "वक्र",
    "start": 3.78
   },
   {
    "word": "हैं।",
    "start": 4.2
   }
  ],
  "words": [
   {
    "word": "You",
    "start": 0.25
   },
   {
    "word": "got",
    "start": 0.25
   },
   {
    "word": "it!",
    "start": 0.76
   },
   {
    "word": "These",
    "start": 1.47
   },
   {
    "word": "boundaries",
    "start": 1.68
   },
   {
    "word": "are",
    "start": 2.2
   },
   {
    "word": "straight,",
    "start": 2.2
   },
   {
    "word": "while",
    "start": 3.17
   },
   {
    "word": "these",
    "start": 3.58
   },
   {
    "word": "are",
    "start": 3.78
   },
   {
    "word": "curved.",
    "start": 3.78
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/71.flac (s15GotIt), 0.00-4.64 s"
 },
 {
  "text": "Tap the closed figure made with straight lines.",
  "shown": "सीधी रेखाओं से बनी बंद आकृति पर टैप करें।",
  "src": "assets/audio/lesson/hi/80_Tap_the_closed_figure_made_with_straight_lines.mp3",
  "duration": 3.68,
  "spoken": [
   {
    "word": "सीधी",
    "start": 0.25
   },
   {
    "word": "रेखाओं",
    "start": 0.78
   },
   {
    "word": "से",
    "start": 1.34
   },
   {
    "word": "बनी",
    "start": 1.56
   },
   {
    "word": "बंद",
    "start": 1.82
   },
   {
    "word": "आकृति",
    "start": 2.22
   },
   {
    "word": "पर",
    "start": 2.62
   },
   {
    "word": "टैप",
    "start": 2.86
   },
   {
    "word": "करें।",
    "start": 3.16
   }
  ],
  "words": [
   {
    "word": "Tap",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.78
   },
   {
    "word": "closed",
    "start": 1.82
   },
   {
    "word": "figure",
    "start": 2.22
   },
   {
    "word": "made",
    "start": 1.82
   },
   {
    "word": "with",
    "start": 2.22
   },
   {
    "word": "straight",
    "start": 0.25
   },
   {
    "word": "lines.",
    "start": 0.78
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/72.flac (s16TapClosedStraight), 0.02-3.70 s"
 },
 {
  "text": "Yes! It is closed and made of straight lines.",
  "shown": "हाँ! यह बंद है और सीधी रेखाओं से बनी है।",
  "src": "assets/audio/lesson/hi/70_Yes_It_is_closed_and_made_of_straight_lines.mp3",
  "duration": 3.9,
  "spoken": [
   {
    "word": "हाँ!",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 0.97
   },
   {
    "word": "बंद",
    "start": 1.22
   },
   {
    "word": "है",
    "start": 1.68
   },
   {
    "word": "और",
    "start": 1.82
   },
   {
    "word": "सीधी",
    "start": 2.1
   },
   {
    "word": "रेखाओं",
    "start": 2.6
   },
   {
    "word": "से",
    "start": 3.08
   },
   {
    "word": "बनी",
    "start": 3.24
   },
   {
    "word": "है।",
    "start": 3.48
   }
  ],
  "words": [
   {
    "word": "Yes!",
    "start": 0.25
   },
   {
    "word": "It",
    "start": 0.97
   },
   {
    "word": "is",
    "start": 1.22
   },
   {
    "word": "closed",
    "start": 1.22
   },
   {
    "word": "and",
    "start": 1.82
   },
   {
    "word": "made",
    "start": 2.1
   },
   {
    "word": "of",
    "start": 2.6
   },
   {
    "word": "straight",
    "start": 2.1
   },
   {
    "word": "lines.",
    "start": 2.6
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/73.flac (s16Yes), 0.04-3.94 s"
 },
 {
  "text": "Not quite. Look for a figure with no gaps and no curves.",
  "shown": "पूरी तरह से सही नहीं। ऐसी आकृति ढूँढें जिसमें न खाली जगह हो, न मोड़।",
  "src": "assets/audio/lesson/hi/50_Not_quite_Look_for_a_figure_with_no_gaps_and_no_curves.mp3",
  "duration": 5.91,
  "spoken": [
   {
    "word": "पूरी",
    "start": 0.25
   },
   {
    "word": "तरह",
    "start": 0.56
   },
   {
    "word": "से",
    "start": 0.8
   },
   {
    "word": "सही",
    "start": 1.08
   },
   {
    "word": "नहीं।",
    "start": 1.36
   },
   {
    "word": "ऐसी",
    "start": 2.13
   },
   {
    "word": "आकृति",
    "start": 2.44
   },
   {
    "word": "ढूँढें",
    "start": 2.92
   },
   {
    "word": "जिसमें",
    "start": 3.52
   },
   {
    "word": "न",
    "start": 3.94
   },
   {
    "word": "खाली",
    "start": 4.02
   },
   {
    "word": "जगह",
    "start": 4.5
   },
   {
    "word": "हो,",
    "start": 4.78
   },
   {
    "word": "न",
    "start": 5.17
   },
   {
    "word": "मोड़।",
    "start": 5.26
   }
  ],
  "words": [
   {
    "word": "Not",
    "start": 0.25
   },
   {
    "word": "quite.",
    "start": 0.8
   },
   {
    "word": "Look",
    "start": 2.92
   },
   {
    "word": "for",
    "start": 2.44
   },
   {
    "word": "a",
    "start": 2.92
   },
   {
    "word": "figure",
    "start": 2.44
   },
   {
    "word": "with",
    "start": 3.94
   },
   {
    "word": "no",
    "start": 4.02
   },
   {
    "word": "gaps",
    "start": 4.02
   },
   {
    "word": "and",
    "start": 4.78
   },
   {
    "word": "no",
    "start": 5.17
   },
   {
    "word": "curves.",
    "start": 5.26
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/74.flac (s16NotQuite), 0.04-5.95 s"
 },
 {
  "text": "We call this a polygon.",
  "shown": "इसे हम बहुभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/17_We_call_this_a_polygon.mp3",
  "duration": 2.32,
  "spoken": [
   {
    "word": "इसे",
    "start": 0.25
   },
   {
    "word": "हम",
    "start": 0.58
   },
   {
    "word": "बहुभुज",
    "start": 0.86
   },
   {
    "word": "कहते",
    "start": 1.48
   },
   {
    "word": "हैं।",
    "start": 1.88
   }
  ],
  "words": [
   {
    "word": "We",
    "start": 0.25
   },
   {
    "word": "call",
    "start": 0.58
   },
   {
    "word": "this",
    "start": 0.86
   },
   {
    "word": "a",
    "start": 1.48
   },
   {
    "word": "polygon.",
    "start": 0.86
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/75.flac (s17CallPolygon), 0.06-2.38 s"
 },
 {
  "text": "A closed figure made of only straight line segments is called a polygon.",
  "shown": "केवल रेखाखंडों से बनी बंद आकृति को बहुभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/18_A_closed_figure_made_of_only_straight_line_segments_is_called.mp3",
  "duration": 4.48,
  "spoken": [
   {
    "word": "केवल",
    "start": 0.25
   },
   {
    "word": "रेखाखंडों",
    "start": 0.62
   },
   {
    "word": "से",
    "start": 1.44
   },
   {
    "word": "बनी",
    "start": 1.62
   },
   {
    "word": "बंद",
    "start": 1.9
   },
   {
    "word": "आकृति",
    "start": 2.26
   },
   {
    "word": "को",
    "start": 2.72
   },
   {
    "word": "बहुभुज",
    "start": 3.2
   },
   {
    "word": "कहते",
    "start": 3.72
   },
   {
    "word": "हैं।",
    "start": 4.08
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "closed",
    "start": 1.9
   },
   {
    "word": "figure",
    "start": 2.26
   },
   {
    "word": "made",
    "start": 1.44
   },
   {
    "word": "of",
    "start": 1.62
   },
   {
    "word": "only",
    "start": 1.62
   },
   {
    "word": "straight",
    "start": 0.62
   },
   {
    "word": "line",
    "start": 0.62
   },
   {
    "word": "segments",
    "start": 0.62
   },
   {
    "word": "is",
    "start": 2.72
   },
   {
    "word": "called",
    "start": 3.2
   },
   {
    "word": "a",
    "start": 3.72
   },
   {
    "word": "polygon.",
    "start": 3.2
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/76.flac (s18Definition), 0.02-4.50 s"
 },
 {
  "text": "Which of these figures are polygons?",
  "shown": "इनमें से कौन-सी आकृतियाँ बहुभुज हैं?",
  "src": "assets/audio/lesson/hi/19_Which_of_these_figures_are_polygons.mp3",
  "duration": 3.04,
  "spoken": [
   {
    "word": "इनमें",
    "start": 0.25
   },
   {
    "word": "से",
    "start": 0.65
   },
   {
    "word": "कौन-सी",
    "start": 0.79
   },
   {
    "word": "आकृतियाँ",
    "start": 1.33
   },
   {
    "word": "बहुभुज",
    "start": 2.07
   },
   {
    "word": "हैं?",
    "start": 2.61
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 0.79
   },
   {
    "word": "of",
    "start": 0.65
   },
   {
    "word": "these",
    "start": 0.79
   },
   {
    "word": "figures",
    "start": 1.33
   },
   {
    "word": "are",
    "start": 2.07
   },
   {
    "word": "polygons?",
    "start": 2.07
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/77.flac (s19WhichPolygons), 0.05-3.09 s"
 },
 {
  "text": "Great job! You identified all the polygons.",
  "shown": "बहुत बढ़िया! आपने सभी बहुभुज पहचान लिए।",
  "src": "assets/audio/lesson/hi/81_Great_job_You_identified_all_the_polygons.mp3",
  "duration": 3.75,
  "spoken": [
   {
    "word": "बहुत",
    "start": 0.25
   },
   {
    "word": "बढ़िया!",
    "start": 0.72
   },
   {
    "word": "आपने",
    "start": 1.53
   },
   {
    "word": "सभी",
    "start": 1.9
   },
   {
    "word": "बहुभुज",
    "start": 2.28
   },
   {
    "word": "पहचान",
    "start": 2.74
   },
   {
    "word": "लिए।",
    "start": 3.2
   }
  ],
  "words": [
   {
    "word": "Great",
    "start": 0.25
   },
   {
    "word": "job!",
    "start": 0.72
   },
   {
    "word": "You",
    "start": 1.53
   },
   {
    "word": "identified",
    "start": 1.9
   },
   {
    "word": "all",
    "start": 2.28
   },
   {
    "word": "the",
    "start": 2.74
   },
   {
    "word": "polygons.",
    "start": 2.28
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/78.flac (s19GreatJob), 0.02-3.77 s"
 },
 {
  "text": "A polygon is closed, with only straight sides.",
  "shown": "बहुभुज बंद होता है, और उसकी सभी भुजाएँ सीधी होती हैं।",
  "src": "assets/audio/lesson/hi/72_A_polygon_is_closed_with_only_straight_sides.mp3",
  "duration": 4.8,
  "spoken": [
   {
    "word": "बहुभुज",
    "start": 0.25
   },
   {
    "word": "बंद",
    "start": 0.93
   },
   {
    "word": "होता",
    "start": 1.39
   },
   {
    "word": "है,",
    "start": 1.69
   },
   {
    "word": "और",
    "start": 2.21
   },
   {
    "word": "उसकी",
    "start": 2.37
   },
   {
    "word": "सभी",
    "start": 2.61
   },
   {
    "word": "भुजाएँ",
    "start": 3.01
   },
   {
    "word": "सीधी",
    "start": 3.57
   },
   {
    "word": "होती",
    "start": 4.05
   },
   {
    "word": "हैं।",
    "start": 4.41
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 0.25
   },
   {
    "word": "is",
    "start": 1.39
   },
   {
    "word": "closed,",
    "start": 0.93
   },
   {
    "word": "with",
    "start": 2.37
   },
   {
    "word": "only",
    "start": 2.61
   },
   {
    "word": "straight",
    "start": 3.57
   },
   {
    "word": "sides.",
    "start": 3.01
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/79.flac (polygonRule), 0.05-4.85 s"
 },
 {
  "text": "That is right! These are the ones.",
  "shown": "बिल्कुल सही! यही वाली हैं।",
  "src": "assets/audio/lesson/hi/71_That_is_right_These_are_the_ones.mp3",
  "duration": 2.4,
  "spoken": [
   {
    "word": "बिल्कुल",
    "start": 0.25
   },
   {
    "word": "सही!",
    "start": 0.71
   },
   {
    "word": "यही",
    "start": 1.31
   },
   {
    "word": "वाली",
    "start": 1.65
   },
   {
    "word": "हैं।",
    "start": 1.99
   }
  ],
  "words": [
   {
    "word": "That",
    "start": 0.25
   },
   {
    "word": "is",
    "start": 0.25
   },
   {
    "word": "right!",
    "start": 0.71
   },
   {
    "word": "These",
    "start": 1.31
   },
   {
    "word": "are",
    "start": 1.31
   },
   {
    "word": "the",
    "start": 1.65
   },
   {
    "word": "ones.",
    "start": 1.99
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/80.flac (fbTheseAreTheOnes), 0.01-2.41 s"
 },
 {
  "text": "Not quite. Try again.",
  "shown": "पूरी तरह से सही नहीं। फिर से प्रयास करें।",
  "src": "assets/audio/lesson/hi/75_Not_quite_Try_again.mp3",
  "duration": 3.19,
  "spoken": [
   {
    "word": "पूरी",
    "start": 0.25
   },
   {
    "word": "तरह",
    "start": 0.54
   },
   {
    "word": "से",
    "start": 0.76
   },
   {
    "word": "सही",
    "start": 1.02
   },
   {
    "word": "नहीं।",
    "start": 1.28
   },
   {
    "word": "फिर",
    "start": 1.93
   },
   {
    "word": "से",
    "start": 2.1
   },
   {
    "word": "प्रयास",
    "start": 2.28
   },
   {
    "word": "करें।",
    "start": 2.66
   }
  ],
  "words": [
   {
    "word": "Not",
    "start": 0.25
   },
   {
    "word": "quite.",
    "start": 0.76
   },
   {
    "word": "Try",
    "start": 1.93
   },
   {
    "word": "again.",
    "start": 2.28
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/81.flac (fbNotQuiteTryAgain), 0.04-3.23 s"
 },
 {
  "text": "These line segments are the sides of the polygon.",
  "shown": "ये रेखाखंड बहुभुज की भुजाएँ हैं।",
  "src": "assets/audio/lesson/hi/20_These_line_segments_are_the_sides_of_the_polygon.mp3",
  "duration": 3.34,
  "spoken": [
   {
    "word": "ये",
    "start": 0.25
   },
   {
    "word": "रेखाखंड",
    "start": 0.58
   },
   {
    "word": "बहुभुज",
    "start": 1.61
   },
   {
    "word": "की",
    "start": 2.26
   },
   {
    "word": "भुजाएँ",
    "start": 2.42
   },
   {
    "word": "हैं।",
    "start": 2.98
   }
  ],
  "words": [
   {
    "word": "These",
    "start": 0.25
   },
   {
    "word": "line",
    "start": 0.58
   },
   {
    "word": "segments",
    "start": 0.58
   },
   {
    "word": "are",
    "start": 1.61
   },
   {
    "word": "the",
    "start": 1.61
   },
   {
    "word": "sides",
    "start": 2.42
   },
   {
    "word": "of",
    "start": 2.42
   },
   {
    "word": "the",
    "start": 2.42
   },
   {
    "word": "polygon.",
    "start": 1.61
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/83.flac (s20Sides), 0.06-3.40 s"
 },
 {
  "text": "The point where two sides meet is called a vertex.",
  "shown": "जिस बिंदु पर दो भुजाएँ मिलती हैं, उसे शीर्ष कहते हैं।",
  "src": "assets/audio/lesson/hi/21_The_point_where_two_sides_meet_is_called_a_vertex.mp3",
  "duration": 4.73,
  "spoken": [
   {
    "word": "जिस",
    "start": 0.25
   },
   {
    "word": "बिंदु",
    "start": 0.63
   },
   {
    "word": "पर",
    "start": 1.07
   },
   {
    "word": "दो",
    "start": 1.33
   },
   {
    "word": "भुजाएँ",
    "start": 1.59
   },
   {
    "word": "मिलती",
    "start": 2.17
   },
   {
    "word": "हैं,",
    "start": 2.53
   },
   {
    "word": "उसे",
    "start": 3.11
   },
   {
    "word": "शीर्ष",
    "start": 3.37
   },
   {
    "word": "कहते",
    "start": 3.89
   },
   {
    "word": "हैं।",
    "start": 4.31
   }
  ],
  "words": [
   {
    "word": "The",
    "start": 0.25
   },
   {
    "word": "point",
    "start": 0.63
   },
   {
    "word": "where",
    "start": 1.07
   },
   {
    "word": "two",
    "start": 1.33
   },
   {
    "word": "sides",
    "start": 1.59
   },
   {
    "word": "meet",
    "start": 2.17
   },
   {
    "word": "is",
    "start": 2.53
   },
   {
    "word": "called",
    "start": 3.11
   },
   {
    "word": "a",
    "start": 3.37
   },
   {
    "word": "vertex.",
    "start": 3.37
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/84.flac (s21Vertex), 0.01-4.74 s"
 },
 {
  "text": "When two sides meet, they also form an angle.",
  "shown": "जब दो भुजाएँ मिलती हैं, तो वे एक कोण भी बनाती हैं।",
  "src": "assets/audio/lesson/hi/22_When_two_sides_meet_they_also_form_an_angle.mp3",
  "duration": 4.45,
  "spoken": [
   {
    "word": "जब",
    "start": 0.25
   },
   {
    "word": "दो",
    "start": 0.57
   },
   {
    "word": "भुजाएँ",
    "start": 0.83
   },
   {
    "word": "मिलती",
    "start": 1.39
   },
   {
    "word": "हैं,",
    "start": 1.81
   },
   {
    "word": "तो",
    "start": 2.43
   },
   {
    "word": "वे",
    "start": 2.55
   },
   {
    "word": "एक",
    "start": 2.77
   },
   {
    "word": "कोण",
    "start": 3.15
   },
   {
    "word": "भी",
    "start": 3.41
   },
   {
    "word": "बनाती",
    "start": 3.59
   },
   {
    "word": "हैं।",
    "start": 4.03
   }
  ],
  "words": [
   {
    "word": "When",
    "start": 0.25
   },
   {
    "word": "two",
    "start": 0.57
   },
   {
    "word": "sides",
    "start": 0.83
   },
   {
    "word": "meet,",
    "start": 1.39
   },
   {
    "word": "they",
    "start": 2.43
   },
   {
    "word": "also",
    "start": 2.55
   },
   {
    "word": "form",
    "start": 2.43
   },
   {
    "word": "an",
    "start": 3.41
   },
   {
    "word": "angle.",
    "start": 3.15
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/85.flac (s22Angle), 0.01-4.46 s"
 },
 {
  "text": "Label the parts of the polygon.",
  "shown": "बहुभुज के भागों के नाम लगाएँ।",
  "src": "assets/audio/lesson/hi/23_Label_the_parts_of_the_polygon.mp3",
  "duration": 2.79,
  "spoken": [
   {
    "word": "बहुभुज",
    "start": 0.25
   },
   {
    "word": "के",
    "start": 0.88
   },
   {
    "word": "भागों",
    "start": 1.14
   },
   {
    "word": "के",
    "start": 1.62
   },
   {
    "word": "नाम",
    "start": 1.82
   },
   {
    "word": "लगाएँ।",
    "start": 2.12
   }
  ],
  "words": [
   {
    "word": "Label",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.88
   },
   {
    "word": "parts",
    "start": 1.14
   },
   {
    "word": "of",
    "start": 1.62
   },
   {
    "word": "the",
    "start": 1.82
   },
   {
    "word": "polygon.",
    "start": 0.25
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/86.flac (s23LabelParts), 0.02-2.81 s"
 },
 {
  "text": "Perfect! Side, vertex and angle — all labelled.",
  "shown": "शानदार! भुजा, शीर्ष और कोण — सबके नाम लग गए।",
  "src": "assets/audio/lesson/hi/73_Perfect_Side_vertex_and_angle_all_labelled.mp3",
  "duration": 4.84,
  "spoken": [
   {
    "word": "शानदार!",
    "start": 0.25
   },
   {
    "word": "भुजा,",
    "start": 1.46
   },
   {
    "word": "शीर्ष",
    "start": 2.22
   },
   {
    "word": "और",
    "start": 2.8
   },
   {
    "word": "कोण",
    "start": 3.06
   },
   {
    "word": "—",
    "start": 3.67
   },
   {
    "word": "सबके",
    "start": 3.67
   },
   {
    "word": "नाम",
    "start": 4.06
   },
   {
    "word": "लग",
    "start": 4.26
   },
   {
    "word": "गए।",
    "start": 4.44
   }
  ],
  "words": [
   {
    "word": "Perfect!",
    "start": 0.25
   },
   {
    "word": "Side,",
    "start": 1.46
   },
   {
    "word": "vertex",
    "start": 2.22
   },
   {
    "word": "and",
    "start": 3.06
   },
   {
    "word": "angle",
    "start": 3.06
   },
   {
    "word": "all",
    "start": 4.06
   },
   {
    "word": "labelled.",
    "start": 4.26
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/87.flac (s23Perfect), 0.02-4.86 s"
 },
 {
  "text": "Let's count the sides of the polygon.",
  "shown": "आइए, बहुभुज की भुजाएँ गिनें।",
  "src": "assets/audio/lesson/hi/88_Lets_count_the_sides_of_the_polygon.mp3",
  "duration": 2.86,
  "spoken": [
   {
    "word": "आइए,",
    "start": 0.25
   },
   {
    "word": "बहुभुज",
    "start": 1.01
   },
   {
    "word": "की",
    "start": 1.61
   },
   {
    "word": "भुजाएँ",
    "start": 1.81
   },
   {
    "word": "गिनें।",
    "start": 2.35
   }
  ],
  "words": [
   {
    "word": "Let's",
    "start": 0.25
   },
   {
    "word": "count",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 1.01
   },
   {
    "word": "sides",
    "start": 1.81
   },
   {
    "word": "of",
    "start": 1.61
   },
   {
    "word": "the",
    "start": 1.81
   },
   {
    "word": "polygon.",
    "start": 1.01
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/88.flac (s24CountSides), 0.03-2.89 s"
 },
 {
  "text": "Count each side carefully and try again.",
  "shown": "हर भुजा ध्यान से गिनें और फिर से प्रयास करें।",
  "src": "assets/audio/lesson/hi/51_Count_each_side_carefully_and_try_again.mp3",
  "duration": 3.7,
  "spoken": [
   {
    "word": "हर",
    "start": 0.25
   },
   {
    "word": "भुजा",
    "start": 0.49
   },
   {
    "word": "ध्यान",
    "start": 0.89
   },
   {
    "word": "से",
    "start": 1.37
   },
   {
    "word": "गिनें",
    "start": 1.61
   },
   {
    "word": "और",
    "start": 2.2
   },
   {
    "word": "फिर",
    "start": 2.37
   },
   {
    "word": "से",
    "start": 2.61
   },
   {
    "word": "प्रयास",
    "start": 2.81
   },
   {
    "word": "करें।",
    "start": 3.17
   }
  ],
  "words": [
   {
    "word": "Count",
    "start": 0.25
   },
   {
    "word": "each",
    "start": 0.49
   },
   {
    "word": "side",
    "start": 0.49
   },
   {
    "word": "carefully",
    "start": 1.61
   },
   {
    "word": "and",
    "start": 2.2
   },
   {
    "word": "try",
    "start": 2.61
   },
   {
    "word": "again.",
    "start": 2.81
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/89.flac (countCarefully), 0.03-3.73 s"
 },
 {
  "text": "Correct! This polygon has five sides.",
  "shown": "सही! इस बहुभुज की 5 भुजाएँ हैं।",
  "src": "assets/audio/lesson/hi/82_Correct_This_polygon_has_five_sides.mp3",
  "duration": 3.55,
  "spoken": [
   {
    "word": "सही!",
    "start": 0.25
   },
   {
    "word": "इस",
    "start": 1.19
   },
   {
    "word": "बहुभुज",
    "start": 1.38
   },
   {
    "word": "की",
    "start": 1.94
   },
   {
    "word": "5",
    "start": 2.38
   },
   {
    "word": "भुजाएँ",
    "start": 2.66
   },
   {
    "word": "हैं।",
    "start": 3.2
   }
  ],
  "words": [
   {
    "word": "Correct!",
    "start": 0.25
   },
   {
    "word": "This",
    "start": 1.19
   },
   {
    "word": "polygon",
    "start": 1.38
   },
   {
    "word": "has",
    "start": 1.94
   },
   {
    "word": "five",
    "start": 2.38
   },
   {
    "word": "sides.",
    "start": 2.66
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/90.flac (s25Correct5), 0.02-3.57 s"
 },
 {
  "text": "Now let's change how it looks.",
  "shown": "अब इसका रूप बदलते हैं।",
  "src": "assets/audio/lesson/hi/26_Now_lets_change_how_it_looks.mp3",
  "duration": 2.26,
  "spoken": [
   {
    "word": "अब",
    "start": 0.25
   },
   {
    "word": "इसका",
    "start": 0.75
   },
   {
    "word": "रूप",
    "start": 1.08
   },
   {
    "word": "बदलते",
    "start": 1.36
   },
   {
    "word": "हैं।",
    "start": 1.86
   }
  ],
  "words": [
   {
    "word": "Now",
    "start": 0.25
   },
   {
    "word": "let's",
    "start": 0.25
   },
   {
    "word": "change",
    "start": 0.75
   },
   {
    "word": "how",
    "start": 1.08
   },
   {
    "word": "it",
    "start": 1.36
   },
   {
    "word": "looks.",
    "start": 1.86
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/91.flac (s26ChangeLooks), 0.04-2.30 s"
 },
 {
  "text": "Drag any vertex. Stretch it, squash it, or resize it.",
  "shown": "कोई भी शीर्ष खींचें। इसे फैलाएँ, दबाएँ या इसका आकार बदलें।",
  "src": "assets/audio/lesson/hi/27_Drag_any_vertex_Stretch_it_squash_it_or_resize_it.mp3",
  "duration": 5.79,
  "spoken": [
   {
    "word": "कोई",
    "start": 0.25
   },
   {
    "word": "भी",
    "start": 0.53
   },
   {
    "word": "शीर्ष",
    "start": 0.77
   },
   {
    "word": "खींचें।",
    "start": 1.21
   },
   {
    "word": "इसे",
    "start": 2.12
   },
   {
    "word": "फैलाएँ,",
    "start": 2.37
   },
   {
    "word": "दबाएँ",
    "start": 3.31
   },
   {
    "word": "या",
    "start": 4.16
   },
   {
    "word": "इसका",
    "start": 4.33
   },
   {
    "word": "आकार",
    "start": 4.69
   },
   {
    "word": "बदलें।",
    "start": 5.17
   }
  ],
  "words": [
   {
    "word": "Drag",
    "start": 0.25
   },
   {
    "word": "any",
    "start": 0.53
   },
   {
    "word": "vertex.",
    "start": 0.77
   },
   {
    "word": "Stretch",
    "start": 2.12
   },
   {
    "word": "it,",
    "start": 2.37
   },
   {
    "word": "squash",
    "start": 3.31
   },
   {
    "word": "it,",
    "start": 4.16
   },
   {
    "word": "or",
    "start": 4.33
   },
   {
    "word": "resize",
    "start": 4.69
   },
   {
    "word": "it.",
    "start": 5.17
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/92.flac (s27DragVertex), 0.01-5.80 s"
 },
 {
  "text": "Whoa! It looks quite different now.",
  "shown": "वाह! अब यह बिल्कुल अलग दिख रहा है।",
  "src": "assets/audio/lesson/hi/28_Whoa_It_looks_quite_different_now.mp3",
  "duration": 3.36,
  "spoken": [
   {
    "word": "वाह!",
    "start": 0.25
   },
   {
    "word": "अब",
    "start": 1.3
   },
   {
    "word": "यह",
    "start": 1.47
   },
   {
    "word": "बिल्कुल",
    "start": 1.65
   },
   {
    "word": "अलग",
    "start": 2.23
   },
   {
    "word": "दिख",
    "start": 2.47
   },
   {
    "word": "रहा",
    "start": 2.65
   },
   {
    "word": "है।",
    "start": 2.93
   }
  ],
  "words": [
   {
    "word": "Whoa!",
    "start": 0.25
   },
   {
    "word": "It",
    "start": 1.3
   },
   {
    "word": "looks",
    "start": 1.47
   },
   {
    "word": "quite",
    "start": 1.65
   },
   {
    "word": "different",
    "start": 2.47
   },
   {
    "word": "now.",
    "start": 2.65
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/94.flac (s28Whoa), 0.01-3.37 s"
 },
 {
  "text": "Its appearance has completely changed.",
  "shown": "इसका रूप पूरी तरह बदल गया है।",
  "src": "assets/audio/lesson/hi/29_Its_appearance_has_completely_changed.mp3",
  "duration": 2.7,
  "spoken": [
   {
    "word": "इसका",
    "start": 0.25
   },
   {
    "word": "रूप",
    "start": 0.64
   },
   {
    "word": "पूरी",
    "start": 1.03
   },
   {
    "word": "तरह",
    "start": 1.36
   },
   {
    "word": "बदल",
    "start": 1.68
   },
   {
    "word": "गया",
    "start": 2.02
   },
   {
    "word": "है।",
    "start": 2.28
   }
  ],
  "words": [
   {
    "word": "Its",
    "start": 0.25
   },
   {
    "word": "appearance",
    "start": 0.64
   },
   {
    "word": "has",
    "start": 1.03
   },
   {
    "word": "completely",
    "start": 1.68
   },
   {
    "word": "changed.",
    "start": 2.02
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/95.flac (s29Appearance), 0.04-2.74 s"
 },
 {
  "text": "But not everything has changed.",
  "shown": "लेकिन सब कुछ नहीं बदला है।",
  "src": "assets/audio/lesson/hi/30_But_not_everything_has_changed.mp3",
  "duration": 2.19,
  "spoken": [
   {
    "word": "लेकिन",
    "start": 0.25
   },
   {
    "word": "सब",
    "start": 0.6
   },
   {
    "word": "कुछ",
    "start": 0.95
   },
   {
    "word": "नहीं",
    "start": 1.12
   },
   {
    "word": "बदला",
    "start": 1.4
   },
   {
    "word": "है।",
    "start": 1.74
   }
  ],
  "words": [
   {
    "word": "But",
    "start": 0.25
   },
   {
    "word": "not",
    "start": 0.6
   },
   {
    "word": "everything",
    "start": 0.95
   },
   {
    "word": "has",
    "start": 1.12
   },
   {
    "word": "changed.",
    "start": 1.4
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/96.flac (s30NotEverything), 0.04-2.23 s"
 },
 {
  "text": "Let's count the sides again.",
  "shown": "आइए, भुजाएँ फिर से गिनें।",
  "src": "assets/audio/lesson/hi/31_Lets_count_the_sides_again.mp3",
  "duration": 2.72,
  "spoken": [
   {
    "word": "आइए,",
    "start": 0.25
   },
   {
    "word": "भुजाएँ",
    "start": 1.07
   },
   {
    "word": "फिर",
    "start": 1.7
   },
   {
    "word": "से",
    "start": 1.94
   },
   {
    "word": "गिनें।",
    "start": 2.2
   }
  ],
  "words": [
   {
    "word": "Let's",
    "start": 0.25
   },
   {
    "word": "count",
    "start": 1.07
   },
   {
    "word": "the",
    "start": 1.7
   },
   {
    "word": "sides",
    "start": 1.07
   },
   {
    "word": "again.",
    "start": 2.2
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/97.flac (s31CountAgain), 0.02-2.74 s"
 },
 {
  "text": "Both polygons still have five sides.",
  "shown": "दोनों बहुभुजों की अब भी 5 भुजाएँ हैं।",
  "src": "assets/audio/lesson/hi/32_Both_polygons_still_have_five_sides.mp3",
  "duration": 3.27,
  "spoken": [
   {
    "word": "दोनों",
    "start": 0.25
   },
   {
    "word": "बहुभुजों",
    "start": 0.68
   },
   {
    "word": "की",
    "start": 1.36
   },
   {
    "word": "अब",
    "start": 1.56
   },
   {
    "word": "भी",
    "start": 1.82
   },
   {
    "word": "5",
    "start": 2.09
   },
   {
    "word": "भुजाएँ",
    "start": 2.42
   },
   {
    "word": "हैं।",
    "start": 2.9
   }
  ],
  "words": [
   {
    "word": "Both",
    "start": 0.25
   },
   {
    "word": "polygons",
    "start": 0.68
   },
   {
    "word": "still",
    "start": 1.36
   },
   {
    "word": "have",
    "start": 1.82
   },
   {
    "word": "five",
    "start": 2.09
   },
   {
    "word": "sides.",
    "start": 2.42
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/98.flac (s32Still5), 0.04-3.31 s"
 },
 {
  "text": "So the number of sides gives us a good way to name polygons.",
  "shown": "इसलिए भुजाओं की संख्या से हम बहुभुजों के नाम आसानी से रख सकते हैं।",
  "src": "assets/audio/lesson/hi/33_So_the_number_of_sides_gives_us_a_good_way_to_name_polygons.mp3",
  "duration": 5.26,
  "spoken": [
   {
    "word": "इसलिए",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 1.07
   },
   {
    "word": "की",
    "start": 1.58
   },
   {
    "word": "संख्या",
    "start": 1.74
   },
   {
    "word": "से",
    "start": 2.18
   },
   {
    "word": "हम",
    "start": 2.42
   },
   {
    "word": "बहुभुजों",
    "start": 2.6
   },
   {
    "word": "के",
    "start": 3.22
   },
   {
    "word": "नाम",
    "start": 3.38
   },
   {
    "word": "आसानी",
    "start": 3.68
   },
   {
    "word": "से",
    "start": 4.24
   },
   {
    "word": "रख",
    "start": 4.38
   },
   {
    "word": "सकते",
    "start": 4.54
   },
   {
    "word": "हैं।",
    "start": 4.78
   }
  ],
  "words": [
   {
    "word": "So",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 1.07
   },
   {
    "word": "number",
    "start": 1.74
   },
   {
    "word": "of",
    "start": 1.74
   },
   {
    "word": "sides",
    "start": 1.07
   },
   {
    "word": "gives",
    "start": 2.42
   },
   {
    "word": "us",
    "start": 2.6
   },
   {
    "word": "a",
    "start": 3.22
   },
   {
    "word": "good",
    "start": 3.38
   },
   {
    "word": "way",
    "start": 3.68
   },
   {
    "word": "to",
    "start": 4.24
   },
   {
    "word": "name",
    "start": 3.38
   },
   {
    "word": "polygons.",
    "start": 2.6
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/99.flac (s33NameBySides), 0.04-5.30 s"
 },
 {
  "text": "A polygon with three sides is called a triangle.",
  "shown": "3 भुजाओं वाले बहुभुज को त्रिभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/34_A_polygon_with_three_sides_is_called_a_triangle.mp3",
  "duration": 3.7,
  "spoken": [
   {
    "word": "3",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.55
   },
   {
    "word": "वाले",
    "start": 1.05
   },
   {
    "word": "बहुभुज",
    "start": 1.43
   },
   {
    "word": "को",
    "start": 1.95
   },
   {
    "word": "त्रिभुज",
    "start": 2.51
   },
   {
    "word": "कहते",
    "start": 2.87
   },
   {
    "word": "हैं।",
    "start": 3.27
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.43
   },
   {
    "word": "with",
    "start": 0.55
   },
   {
    "word": "three",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.55
   },
   {
    "word": "is",
    "start": 1.95
   },
   {
    "word": "called",
    "start": 2.51
   },
   {
    "word": "a",
    "start": 2.87
   },
   {
    "word": "triangle.",
    "start": 2.51
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/100.flac (s34Triangle), 0.03-3.73 s"
 },
 {
  "text": "A polygon with four sides is called a quadrilateral.",
  "shown": "4 भुजाओं वाले बहुभुज को चतुर्भुज कहते हैं।",
  "src": "assets/audio/lesson/hi/35_A_polygon_with_four_sides_is_called_a_quadrilateral.mp3",
  "duration": 3.53,
  "spoken": [
   {
    "word": "4",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.6
   },
   {
    "word": "वाले",
    "start": 1.04
   },
   {
    "word": "बहुभुज",
    "start": 1.36
   },
   {
    "word": "को",
    "start": 1.86
   },
   {
    "word": "चतुर्भुज",
    "start": 2.23
   },
   {
    "word": "कहते",
    "start": 2.76
   },
   {
    "word": "हैं।",
    "start": 3.14
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.36
   },
   {
    "word": "with",
    "start": 0.6
   },
   {
    "word": "four",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.6
   },
   {
    "word": "is",
    "start": 1.86
   },
   {
    "word": "called",
    "start": 2.23
   },
   {
    "word": "a",
    "start": 2.76
   },
   {
    "word": "quadrilateral.",
    "start": 2.23
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/101.flac (s35Quadrilateral), 0.06-3.59 s"
 },
 {
  "text": "Select all the quadrilaterals.",
  "shown": "सभी चतुर्भुज चुनें।",
  "src": "assets/audio/lesson/hi/36_Select_all_the_quadrilaterals.mp3",
  "duration": 1.89,
  "spoken": [
   {
    "word": "सभी",
    "start": 0.25
   },
   {
    "word": "चतुर्भुज",
    "start": 0.66
   },
   {
    "word": "चुनें।",
    "start": 1.28
   }
  ],
  "words": [
   {
    "word": "Select",
    "start": 0.25
   },
   {
    "word": "all",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.66
   },
   {
    "word": "quadrilaterals.",
    "start": 0.66
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/102.flac (s36SelectQuadrilaterals), 0.02-1.91 s"
 },
 {
  "text": "That's right! Quadrilaterals are polygons with four sides.",
  "shown": "बिल्कुल सही! चतुर्भुज 4 भुजाओं वाले बहुभुज होते हैं।",
  "src": "assets/audio/lesson/hi/83_Thats_right_Quadrilaterals_are_polygons.mp3",
  "duration": 4.6,
  "spoken": [
   {
    "word": "बिल्कुल",
    "start": 0.25
   },
   {
    "word": "सही!",
    "start": 0.82
   },
   {
    "word": "चतुर्भुज",
    "start": 1.6
   },
   {
    "word": "4",
    "start": 2.51
   },
   {
    "word": "भुजाओं",
    "start": 2.8
   },
   {
    "word": "वाले",
    "start": 3.22
   },
   {
    "word": "बहुभुज",
    "start": 3.46
   },
   {
    "word": "होते",
    "start": 3.94
   },
   {
    "word": "हैं।",
    "start": 4.22
   }
  ],
  "words": [
   {
    "word": "That's",
    "start": 0.25
   },
   {
    "word": "right!",
    "start": 0.82
   },
   {
    "word": "Quadrilaterals",
    "start": 1.6
   },
   {
    "word": "are",
    "start": 2.51
   },
   {
    "word": "polygons",
    "start": 3.46
   },
   {
    "word": "with",
    "start": 3.22
   },
   {
    "word": "four",
    "start": 2.51
   },
   {
    "word": "sides.",
    "start": 2.8
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/103.flac (s36ThatsRight), 0.06-4.66 s"
 },
 {
  "text": "Quadrilaterals are polygons with four sides.",
  "shown": "चतुर्भुज 4 भुजाओं वाले बहुभुज होते हैं।",
  "src": "assets/audio/lesson/hi/84_Quadrilaterals_are_polygons_with_four_sides.mp3",
  "duration": 3.35,
  "spoken": [
   {
    "word": "चतुर्भुज",
    "start": 0.25
   },
   {
    "word": "4",
    "start": 1.09
   },
   {
    "word": "भुजाओं",
    "start": 1.4
   },
   {
    "word": "वाले",
    "start": 1.86
   },
   {
    "word": "बहुभुज",
    "start": 2.16
   },
   {
    "word": "होते",
    "start": 2.64
   },
   {
    "word": "हैं।",
    "start": 2.94
   }
  ],
  "words": [
   {
    "word": "Quadrilaterals",
    "start": 0.25
   },
   {
    "word": "are",
    "start": 1.09
   },
   {
    "word": "polygons",
    "start": 2.16
   },
   {
    "word": "with",
    "start": 1.86
   },
   {
    "word": "four",
    "start": 1.09
   },
   {
    "word": "sides.",
    "start": 1.4
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/104.flac (s36Rule), 0.02-3.37 s"
 },
 {
  "text": "Is this shape a quadrilateral?",
  "shown": "क्या यह आकृति चतुर्भुज है?",
  "src": "assets/audio/lesson/hi/85_Is_this_shape_a_quadrilateral.mp3",
  "duration": 2.32,
  "spoken": [
   {
    "word": "क्या",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 0.51
   },
   {
    "word": "आकृति",
    "start": 0.67
   },
   {
    "word": "चतुर्भुज",
    "start": 1.25
   },
   {
    "word": "है?",
    "start": 1.91
   }
  ],
  "words": [
   {
    "word": "Is",
    "start": 0.25
   },
   {
    "word": "this",
    "start": 0.51
   },
   {
    "word": "shape",
    "start": 0.67
   },
   {
    "word": "a",
    "start": 1.25
   },
   {
    "word": "quadrilateral?",
    "start": 1.25
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/105.flac (s36IsThisQuad), 0.01-2.33 s"
 },
 {
  "text": "A polygon with five sides is called a pentagon.",
  "shown": "5 भुजाओं वाले बहुभुज को पंचभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/37_A_polygon_with_five_sides_is_called_a_pentagon.mp3",
  "duration": 3.74,
  "spoken": [
   {
    "word": "5",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.61
   },
   {
    "word": "वाले",
    "start": 1.09
   },
   {
    "word": "बहुभुज",
    "start": 1.45
   },
   {
    "word": "को",
    "start": 1.97
   },
   {
    "word": "पंचभुज",
    "start": 2.41
   },
   {
    "word": "कहते",
    "start": 2.97
   },
   {
    "word": "हैं।",
    "start": 3.33
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.45
   },
   {
    "word": "with",
    "start": 0.61
   },
   {
    "word": "five",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.61
   },
   {
    "word": "is",
    "start": 1.97
   },
   {
    "word": "called",
    "start": 2.41
   },
   {
    "word": "a",
    "start": 2.97
   },
   {
    "word": "pentagon.",
    "start": 2.41
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/106.flac (s37Pentagon), 0.01-3.75 s"
 },
 {
  "text": "A polygon with six sides is called a hexagon.",
  "shown": "6 भुजाओं वाले बहुभुज को षट्भुज कहते हैं।",
  "src": "assets/audio/lesson/hi/38_A_polygon_with_six_sides_is_called_a_hexagon.mp3",
  "duration": 3.6,
  "spoken": [
   {
    "word": "6",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.47
   },
   {
    "word": "वाले",
    "start": 1.03
   },
   {
    "word": "बहुभुज",
    "start": 1.35
   },
   {
    "word": "को",
    "start": 1.87
   },
   {
    "word": "षट्भुज",
    "start": 2.31
   },
   {
    "word": "कहते",
    "start": 2.83
   },
   {
    "word": "हैं।",
    "start": 3.19
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.35
   },
   {
    "word": "with",
    "start": 0.47
   },
   {
    "word": "six",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.47
   },
   {
    "word": "is",
    "start": 1.87
   },
   {
    "word": "called",
    "start": 2.31
   },
   {
    "word": "a",
    "start": 2.83
   },
   {
    "word": "hexagon.",
    "start": 2.31
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/107.flac (s38Hexagon), 0.07-3.67 s"
 },
 {
  "text": "A polygon with seven sides is called a heptagon.",
  "shown": "7 भुजाओं वाले बहुभुज को सप्तभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/39_A_polygon_with_seven_sides_is_called_a_heptagon.mp3",
  "duration": 3.98,
  "spoken": [
   {
    "word": "7",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.7
   },
   {
    "word": "वाले",
    "start": 1.2
   },
   {
    "word": "बहुभुज",
    "start": 1.52
   },
   {
    "word": "को",
    "start": 2.06
   },
   {
    "word": "सप्तभुज",
    "start": 2.55
   },
   {
    "word": "कहते",
    "start": 3.2
   },
   {
    "word": "हैं।",
    "start": 3.58
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.52
   },
   {
    "word": "with",
    "start": 0.7
   },
   {
    "word": "seven",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.7
   },
   {
    "word": "is",
    "start": 2.06
   },
   {
    "word": "called",
    "start": 2.55
   },
   {
    "word": "a",
    "start": 3.2
   },
   {
    "word": "heptagon.",
    "start": 2.55
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/108.flac (s39Heptagon), 0.00-3.98 s"
 },
 {
  "text": "A polygon with eight sides is called an octagon.",
  "shown": "8 भुजाओं वाले बहुभुज को अष्टभुज कहते हैं।",
  "src": "assets/audio/lesson/hi/40_A_polygon_with_eight_sides_is_called_an_octagon.mp3",
  "duration": 3.86,
  "spoken": [
   {
    "word": "8",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.54
   },
   {
    "word": "वाले",
    "start": 1.08
   },
   {
    "word": "बहुभुज",
    "start": 1.48
   },
   {
    "word": "को",
    "start": 2.02
   },
   {
    "word": "अष्टभुज",
    "start": 2.57
   },
   {
    "word": "कहते",
    "start": 3.1
   },
   {
    "word": "हैं।",
    "start": 3.46
   }
  ],
  "words": [
   {
    "word": "A",
    "start": 0.25
   },
   {
    "word": "polygon",
    "start": 1.48
   },
   {
    "word": "with",
    "start": 0.54
   },
   {
    "word": "eight",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.54
   },
   {
    "word": "is",
    "start": 2.02
   },
   {
    "word": "called",
    "start": 2.57
   },
   {
    "word": "an",
    "start": 3.1
   },
   {
    "word": "octagon.",
    "start": 2.57
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/109.flac (s40Octagon), 0.02-3.88 s"
 },
 {
  "text": "Let's recall what we learnt today.",
  "shown": "आइए, याद करें कि आज हमने क्या सीखा।",
  "src": "assets/audio/lesson/hi/91_Lets_recall_what_we_learnt_today.mp3",
  "duration": 3.55,
  "spoken": [
   {
    "word": "आइए,",
    "start": 0.25
   },
   {
    "word": "याद",
    "start": 1.06
   },
   {
    "word": "करें",
    "start": 1.46
   },
   {
    "word": "कि",
    "start": 1.78
   },
   {
    "word": "आज",
    "start": 2.0
   },
   {
    "word": "हमने",
    "start": 2.3
   },
   {
    "word": "क्या",
    "start": 2.6
   },
   {
    "word": "सीखा।",
    "start": 2.96
   }
  ],
  "words": [
   {
    "word": "Let's",
    "start": 0.25
   },
   {
    "word": "recall",
    "start": 1.06
   },
   {
    "word": "what",
    "start": 1.46
   },
   {
    "word": "we",
    "start": 2.0
   },
   {
    "word": "learnt",
    "start": 2.3
   },
   {
    "word": "today.",
    "start": 2.6
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/110.flac (recapRecall), 0.04-3.59 s"
 },
 {
  "text": "Polygons have different names based on their number of sides.",
  "shown": "भुजाओं की संख्या के आधार पर बहुभुजों के अलग-अलग नाम होते हैं।",
  "src": "assets/audio/lesson/hi/92_Polygons_have_different_names_based_on_their_number_of_sides.mp3",
  "duration": 4.83,
  "spoken": [
   {
    "word": "भुजाओं",
    "start": 0.25
   },
   {
    "word": "की",
    "start": 0.79
   },
   {
    "word": "संख्या",
    "start": 0.97
   },
   {
    "word": "के",
    "start": 1.43
   },
   {
    "word": "आधार",
    "start": 1.57
   },
   {
    "word": "पर",
    "start": 1.97
   },
   {
    "word": "बहुभुजों",
    "start": 2.51
   },
   {
    "word": "के",
    "start": 3.17
   },
   {
    "word": "अलग-अलग",
    "start": 3.39
   },
   {
    "word": "नाम",
    "start": 3.89
   },
   {
    "word": "होते",
    "start": 4.15
   },
   {
    "word": "हैं।",
    "start": 4.43
   }
  ],
  "words": [
   {
    "word": "Polygons",
    "start": 2.51
   },
   {
    "word": "have",
    "start": 0.79
   },
   {
    "word": "different",
    "start": 0.97
   },
   {
    "word": "names",
    "start": 1.43
   },
   {
    "word": "based",
    "start": 1.57
   },
   {
    "word": "on",
    "start": 2.51
   },
   {
    "word": "their",
    "start": 3.17
   },
   {
    "word": "number",
    "start": 0.97
   },
   {
    "word": "of",
    "start": 3.89
   },
   {
    "word": "sides.",
    "start": 0.25
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/111.flac (recapNames), 0.03-4.86 s"
 },
 {
  "text": "Which of these are polygons?",
  "shown": "इनमें से कौन-से बहुभुज हैं?",
  "src": "assets/audio/lesson/hi/77_Select_polygons.mp3",
  "duration": 2.48,
  "spoken": [
   {
    "word": "इनमें",
    "start": 0.25
   },
   {
    "word": "से",
    "start": 0.64
   },
   {
    "word": "कौन-से",
    "start": 0.87
   },
   {
    "word": "बहुभुज",
    "start": 1.42
   },
   {
    "word": "हैं?",
    "start": 2.0
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 0.87
   },
   {
    "word": "of",
    "start": 0.64
   },
   {
    "word": "these",
    "start": 0.87
   },
   {
    "word": "are",
    "start": 1.42
   },
   {
    "word": "polygons?",
    "start": 1.42
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/112.flac (c1WhichPolygons), 0.06-2.54 s"
 },
 {
  "text": "Yes! Closed, with only straight sides.",
  "shown": "हाँ! बंद, और केवल सीधी भुजाएँ।",
  "src": "assets/audio/lesson/hi/52_Yes_Closed_with_only_straight_sides.mp3",
  "duration": 3.64,
  "spoken": [
   {
    "word": "हाँ!",
    "start": 0.25
   },
   {
    "word": "बंद,",
    "start": 1.15
   },
   {
    "word": "और",
    "start": 1.89
   },
   {
    "word": "केवल",
    "start": 2.08
   },
   {
    "word": "सीधी",
    "start": 2.48
   },
   {
    "word": "भुजाएँ।",
    "start": 2.92
   }
  ],
  "words": [
   {
    "word": "Yes!",
    "start": 0.25
   },
   {
    "word": "Closed,",
    "start": 1.15
   },
   {
    "word": "with",
    "start": 1.89
   },
   {
    "word": "only",
    "start": 2.08
   },
   {
    "word": "straight",
    "start": 2.48
   },
   {
    "word": "sides.",
    "start": 2.92
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/113.flac (c1Yes), 0.02-3.66 s"
 },
 {
  "text": "Not quite! A polygon is closed with only straight sides.",
  "shown": "पूरी तरह से सही नहीं! बहुभुज बंद होता है और उसकी केवल सीधी भुजाएँ होती हैं।",
  "src": "assets/audio/lesson/hi/87_Not_quite_A_polygon_is_closed.mp3",
  "duration": 6.46,
  "spoken": [
   {
    "word": "पूरी",
    "start": 0.25
   },
   {
    "word": "तरह",
    "start": 0.57
   },
   {
    "word": "से",
    "start": 0.87
   },
   {
    "word": "सही",
    "start": 1.11
   },
   {
    "word": "नहीं!",
    "start": 1.43
   },
   {
    "word": "बहुभुज",
    "start": 2.11
   },
   {
    "word": "बंद",
    "start": 2.67
   },
   {
    "word": "होता",
    "start": 3.11
   },
   {
    "word": "है",
    "start": 3.43
   },
   {
    "word": "और",
    "start": 3.93
   },
   {
    "word": "उसकी",
    "start": 4.13
   },
   {
    "word": "केवल",
    "start": 4.39
   },
   {
    "word": "सीधी",
    "start": 4.79
   },
   {
    "word": "भुजाएँ",
    "start": 5.31
   },
   {
    "word": "होती",
    "start": 5.81
   },
   {
    "word": "हैं।",
    "start": 6.07
   }
  ],
  "words": [
   {
    "word": "Not",
    "start": 0.25
   },
   {
    "word": "quite!",
    "start": 0.87
   },
   {
    "word": "A",
    "start": 2.11
   },
   {
    "word": "polygon",
    "start": 2.11
   },
   {
    "word": "is",
    "start": 3.11
   },
   {
    "word": "closed",
    "start": 2.67
   },
   {
    "word": "with",
    "start": 4.13
   },
   {
    "word": "only",
    "start": 4.39
   },
   {
    "word": "straight",
    "start": 4.79
   },
   {
    "word": "sides.",
    "start": 5.31
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/114.flac (c1NotQuite), 0.03-6.49 s"
 },
 {
  "text": "Classify the figures as a polygon or not a polygon.",
  "shown": "आकृतियों को बहुभुज या बहुभुज नहीं में बाँटें।",
  "src": "assets/audio/lesson/hi/43_Classify_the_figures_as_a_polygon_or_not_a_polygon.mp3",
  "duration": 4.26,
  "spoken": [
   {
    "word": "आकृतियों",
    "start": 0.25
   },
   {
    "word": "को",
    "start": 0.94
   },
   {
    "word": "बहुभुज",
    "start": 1.2
   },
   {
    "word": "या",
    "start": 2.03
   },
   {
    "word": "बहुभुज",
    "start": 2.3
   },
   {
    "word": "नहीं",
    "start": 2.94
   },
   {
    "word": "में",
    "start": 3.5
   },
   {
    "word": "बाँटें।",
    "start": 3.62
   }
  ],
  "words": [
   {
    "word": "Classify",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.25
   },
   {
    "word": "figures",
    "start": 0.25
   },
   {
    "word": "as",
    "start": 1.2
   },
   {
    "word": "a",
    "start": 2.03
   },
   {
    "word": "polygon",
    "start": 1.2
   },
   {
    "word": "or",
    "start": 2.3
   },
   {
    "word": "not",
    "start": 2.94
   },
   {
    "word": "a",
    "start": 3.5
   },
   {
    "word": "polygon.",
    "start": 2.3
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/115.flac (c2Classify), 0.04-4.30 s"
 },
 {
  "text": "Great job! You sorted the figures correctly.",
  "shown": "बहुत बढ़िया! आपने आकृतियों को सही-सही बाँटा।",
  "src": "assets/audio/lesson/hi/55_Great_job_You_sorted_the_figures_correctly.mp3",
  "duration": 3.79,
  "spoken": [
   {
    "word": "बहुत",
    "start": 0.25
   },
   {
    "word": "बढ़िया!",
    "start": 0.66
   },
   {
    "word": "आपने",
    "start": 1.43
   },
   {
    "word": "आकृतियों",
    "start": 1.78
   },
   {
    "word": "को",
    "start": 2.36
   },
   {
    "word": "सही-सही",
    "start": 2.54
   },
   {
    "word": "बाँटा।",
    "start": 3.14
   }
  ],
  "words": [
   {
    "word": "Great",
    "start": 0.25
   },
   {
    "word": "job!",
    "start": 0.66
   },
   {
    "word": "You",
    "start": 1.43
   },
   {
    "word": "sorted",
    "start": 1.78
   },
   {
    "word": "the",
    "start": 2.36
   },
   {
    "word": "figures",
    "start": 1.78
   },
   {
    "word": "correctly.",
    "start": 3.14
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/117.flac (c2GreatJob), 0.02-3.81 s"
 },
 {
  "text": "Wrong group. Check for gaps or curved sides.",
  "shown": "गलत समूह। खाली जगह या वक्र भुजाएँ देखें।",
  "src": "assets/audio/lesson/hi/56_Wrong_group_Check_for_gaps_or_curved_sides.mp3",
  "duration": 4.2,
  "spoken": [
   {
    "word": "गलत",
    "start": 0.25
   },
   {
    "word": "समूह।",
    "start": 0.7
   },
   {
    "word": "खाली",
    "start": 1.67
   },
   {
    "word": "जगह",
    "start": 2.12
   },
   {
    "word": "या",
    "start": 2.46
   },
   {
    "word": "वक्र",
    "start": 2.72
   },
   {
    "word": "भुजाएँ",
    "start": 3.08
   },
   {
    "word": "देखें।",
    "start": 3.58
   }
  ],
  "words": [
   {
    "word": "Wrong",
    "start": 0.25
   },
   {
    "word": "group.",
    "start": 0.7
   },
   {
    "word": "Check",
    "start": 1.67
   },
   {
    "word": "for",
    "start": 2.12
   },
   {
    "word": "gaps",
    "start": 1.67
   },
   {
    "word": "or",
    "start": 2.72
   },
   {
    "word": "curved",
    "start": 2.72
   },
   {
    "word": "sides.",
    "start": 3.08
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/118.flac (c2WrongGroup), 0.02-4.22 s"
 },
 {
  "text": "Polygons are closed, with only straight sides. Try again.",
  "shown": "बहुभुज बंद होते हैं, और उनकी केवल सीधी भुजाएँ होती हैं। फिर से प्रयास करें।",
  "src": "assets/audio/lesson/hi/57_Polygons_are_closed_with_only_straight_sides_Try_again.mp3",
  "duration": 6.24,
  "spoken": [
   {
    "word": "बहुभुज",
    "start": 0.25
   },
   {
    "word": "बंद",
    "start": 1.01
   },
   {
    "word": "होते",
    "start": 1.47
   },
   {
    "word": "हैं,",
    "start": 1.79
   },
   {
    "word": "और",
    "start": 2.33
   },
   {
    "word": "उनकी",
    "start": 2.49
   },
   {
    "word": "केवल",
    "start": 2.79
   },
   {
    "word": "सीधी",
    "start": 3.17
   },
   {
    "word": "भुजाएँ",
    "start": 3.65
   },
   {
    "word": "होती",
    "start": 4.15
   },
   {
    "word": "हैं।",
    "start": 4.41
   },
   {
    "word": "फिर",
    "start": 5.01
   },
   {
    "word": "से",
    "start": 5.17
   },
   {
    "word": "प्रयास",
    "start": 5.37
   },
   {
    "word": "करें।",
    "start": 5.75
   }
  ],
  "words": [
   {
    "word": "Polygons",
    "start": 0.25
   },
   {
    "word": "are",
    "start": 1.01
   },
   {
    "word": "closed,",
    "start": 1.01
   },
   {
    "word": "with",
    "start": 2.33
   },
   {
    "word": "only",
    "start": 2.79
   },
   {
    "word": "straight",
    "start": 3.17
   },
   {
    "word": "sides.",
    "start": 3.65
   },
   {
    "word": "Try",
    "start": 5.01
   },
   {
    "word": "again.",
    "start": 5.37
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/119.flac (c2Rule), 0.05-6.29 s"
 },
 {
  "text": "Which figure is NOT a polygon?",
  "shown": "कौन-सी आकृति बहुभुज नहीं है?",
  "src": "assets/audio/lesson/hi/78_Not_a_polygon.mp3",
  "duration": 2.47,
  "spoken": [
   {
    "word": "कौन-सी",
    "start": 0.25
   },
   {
    "word": "आकृति",
    "start": 0.69
   },
   {
    "word": "बहुभुज",
    "start": 1.19
   },
   {
    "word": "नहीं",
    "start": 1.77
   },
   {
    "word": "है?",
    "start": 2.09
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 0.25
   },
   {
    "word": "figure",
    "start": 0.69
   },
   {
    "word": "is",
    "start": 0.69
   },
   {
    "word": "NOT",
    "start": 1.19
   },
   {
    "word": "a",
    "start": 1.77
   },
   {
    "word": "polygon?",
    "start": 1.19
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/120.flac (c3WhichNot), 0.00-2.46 s"
 },
 {
  "text": "You found it! That is not a polygon.",
  "shown": "आपने ढूँढ लिया! वह बहुभुज नहीं है।",
  "src": "assets/audio/lesson/hi/58_You_found_it_That_is_not_a_polygon.mp3",
  "duration": 3.58,
  "spoken": [
   {
    "word": "आपने",
    "start": 0.25
   },
   {
    "word": "ढूँढ",
    "start": 0.68
   },
   {
    "word": "लिया!",
    "start": 1.08
   },
   {
    "word": "वह",
    "start": 1.85
   },
   {
    "word": "बहुभुज",
    "start": 2.14
   },
   {
    "word": "नहीं",
    "start": 2.76
   },
   {
    "word": "है।",
    "start": 3.1
   }
  ],
  "words": [
   {
    "word": "You",
    "start": 0.25
   },
   {
    "word": "found",
    "start": 0.68
   },
   {
    "word": "it!",
    "start": 1.08
   },
   {
    "word": "That",
    "start": 1.85
   },
   {
    "word": "is",
    "start": 1.85
   },
   {
    "word": "not",
    "start": 2.14
   },
   {
    "word": "a",
    "start": 2.76
   },
   {
    "word": "polygon.",
    "start": 2.14
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/121.flac (c3Found), 0.02-3.60 s"
 },
 {
  "text": "Which figure breaks the rule for a polygon?",
  "shown": "कौन-सी आकृति बहुभुज का नियम तोड़ती है?",
  "src": "assets/audio/lesson/hi/59_Which_figure_breaks_the_rule_for_a_polygon.mp3",
  "duration": 3.19,
  "spoken": [
   {
    "word": "कौन-सी",
    "start": 0.25
   },
   {
    "word": "आकृति",
    "start": 0.71
   },
   {
    "word": "बहुभुज",
    "start": 1.21
   },
   {
    "word": "का",
    "start": 1.81
   },
   {
    "word": "नियम",
    "start": 1.99
   },
   {
    "word": "तोड़ती",
    "start": 2.29
   },
   {
    "word": "है?",
    "start": 2.79
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 0.25
   },
   {
    "word": "figure",
    "start": 0.71
   },
   {
    "word": "breaks",
    "start": 0.71
   },
   {
    "word": "the",
    "start": 1.21
   },
   {
    "word": "rule",
    "start": 1.81
   },
   {
    "word": "for",
    "start": 1.99
   },
   {
    "word": "a",
    "start": 2.29
   },
   {
    "word": "polygon?",
    "start": 1.21
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/122.flac (c3BreaksRule), 0.03-3.22 s"
 },
 {
  "text": "Is it closed? Does it have only straight sides?",
  "shown": "क्या यह बंद है? क्या इसकी केवल सीधी भुजाएँ हैं?",
  "src": "assets/audio/lesson/hi/53_Is_it_closed_Does_it_have_only_straight_sides.mp3",
  "duration": 4.4,
  "spoken": [
   {
    "word": "क्या",
    "start": 0.25
   },
   {
    "word": "यह",
    "start": 0.52
   },
   {
    "word": "बंद",
    "start": 0.7
   },
   {
    "word": "है?",
    "start": 1.16
   },
   {
    "word": "क्या",
    "start": 1.95
   },
   {
    "word": "इसकी",
    "start": 2.16
   },
   {
    "word": "केवल",
    "start": 2.52
   },
   {
    "word": "सीधी",
    "start": 2.92
   },
   {
    "word": "भुजाएँ",
    "start": 3.42
   },
   {
    "word": "हैं?",
    "start": 4.04
   }
  ],
  "words": [
   {
    "word": "Is",
    "start": 0.25
   },
   {
    "word": "it",
    "start": 0.52
   },
   {
    "word": "closed?",
    "start": 0.7
   },
   {
    "word": "Does",
    "start": 1.95
   },
   {
    "word": "it",
    "start": 2.16
   },
   {
    "word": "have",
    "start": 2.52
   },
   {
    "word": "only",
    "start": 2.92
   },
   {
    "word": "straight",
    "start": 2.92
   },
   {
    "word": "sides?",
    "start": 3.42
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/123.flac (c3Questions), 0.08-4.48 s"
 },
 {
  "text": "Which of these are pentagons?",
  "shown": "इनमें से कौन-से पंचभुज हैं?",
  "src": "assets/audio/lesson/hi/79_Select_pentagons.mp3",
  "duration": 2.59,
  "spoken": [
   {
    "word": "इनमें",
    "start": 0.25
   },
   {
    "word": "से",
    "start": 0.69
   },
   {
    "word": "कौन-से",
    "start": 1.0
   },
   {
    "word": "पंचभुज",
    "start": 1.59
   },
   {
    "word": "हैं?",
    "start": 2.17
   }
  ],
  "words": [
   {
    "word": "Which",
    "start": 1.0
   },
   {
    "word": "of",
    "start": 0.69
   },
   {
    "word": "these",
    "start": 1.0
   },
   {
    "word": "are",
    "start": 1.59
   },
   {
    "word": "pentagons?",
    "start": 1.59
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/124.flac (c4WhichPentagons), 0.01-2.60 s"
 },
 {
  "text": "Exactly! A pentagon always has five sides.",
  "shown": "बिल्कुल! पंचभुज की हमेशा 5 भुजाएँ होती हैं।",
  "src": "assets/audio/lesson/hi/60_Exactly_A_pentagon_always_has_five_sides.mp3",
  "duration": 4.44,
  "spoken": [
   {
    "word": "बिल्कुल!",
    "start": 0.25
   },
   {
    "word": "पंचभुज",
    "start": 1.31
   },
   {
    "word": "की",
    "start": 1.89
   },
   {
    "word": "हमेशा",
    "start": 2.11
   },
   {
    "word": "5",
    "start": 3.0
   },
   {
    "word": "भुजाएँ",
    "start": 3.29
   },
   {
    "word": "होती",
    "start": 3.79
   },
   {
    "word": "हैं।",
    "start": 4.03
   }
  ],
  "words": [
   {
    "word": "Exactly!",
    "start": 0.25
   },
   {
    "word": "A",
    "start": 1.31
   },
   {
    "word": "pentagon",
    "start": 1.31
   },
   {
    "word": "always",
    "start": 2.11
   },
   {
    "word": "has",
    "start": 3.0
   },
   {
    "word": "five",
    "start": 3.0
   },
   {
    "word": "sides.",
    "start": 3.29
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/125.flac (c4Exactly), 0.03-4.47 s"
 },
 {
  "text": "Count the sides of each figure carefully.",
  "shown": "हर आकृति की भुजाएँ ध्यान से गिनें।",
  "src": "assets/audio/lesson/hi/61_Count_the_sides_of_each_figure_carefully.mp3",
  "duration": 3.19,
  "spoken": [
   {
    "word": "हर",
    "start": 0.25
   },
   {
    "word": "आकृति",
    "start": 0.56
   },
   {
    "word": "की",
    "start": 1.16
   },
   {
    "word": "भुजाएँ",
    "start": 1.32
   },
   {
    "word": "ध्यान",
    "start": 2.05
   },
   {
    "word": "से",
    "start": 2.46
   },
   {
    "word": "गिनें।",
    "start": 2.7
   }
  ],
  "words": [
   {
    "word": "Count",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.56
   },
   {
    "word": "sides",
    "start": 1.32
   },
   {
    "word": "of",
    "start": 1.32
   },
   {
    "word": "each",
    "start": 2.05
   },
   {
    "word": "figure",
    "start": 0.56
   },
   {
    "word": "carefully.",
    "start": 2.7
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/126.flac (c4CountEach), 0.06-3.25 s"
 },
 {
  "text": "Look for every figure with exactly five sides.",
  "shown": "ठीक 5 भुजाओं वाली हर आकृति ढूँढें।",
  "src": "assets/audio/lesson/hi/62_Look_for_every_figure_with_exactly_five_sides.mp3",
  "duration": 3.21,
  "spoken": [
   {
    "word": "ठीक",
    "start": 0.25
   },
   {
    "word": "5",
    "start": 0.71
   },
   {
    "word": "भुजाओं",
    "start": 1.08
   },
   {
    "word": "वाली",
    "start": 1.48
   },
   {
    "word": "हर",
    "start": 1.8
   },
   {
    "word": "आकृति",
    "start": 2.1
   },
   {
    "word": "ढूँढें।",
    "start": 2.54
   }
  ],
  "words": [
   {
    "word": "Look",
    "start": 2.54
   },
   {
    "word": "for",
    "start": 0.25
   },
   {
    "word": "every",
    "start": 0.71
   },
   {
    "word": "figure",
    "start": 2.1
   },
   {
    "word": "with",
    "start": 1.48
   },
   {
    "word": "exactly",
    "start": 1.8
   },
   {
    "word": "five",
    "start": 0.71
   },
   {
    "word": "sides.",
    "start": 1.08
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/127.flac (c4LookFor5), 0.04-3.25 s"
 },
 {
  "text": "Classify each figure as a hexagon or a heptagon.",
  "shown": "हर आकृति को षट्भुज या सप्तभुज में बाँटें।",
  "src": "assets/audio/lesson/hi/46_Classify_each_figure_as_a_hexagon_or_a_heptagon.mp3",
  "duration": 4.13,
  "spoken": [
   {
    "word": "हर",
    "start": 0.25
   },
   {
    "word": "आकृति",
    "start": 0.53
   },
   {
    "word": "को",
    "start": 1.05
   },
   {
    "word": "षट्भुज",
    "start": 1.6
   },
   {
    "word": "या",
    "start": 2.51
   },
   {
    "word": "सप्तभुज",
    "start": 2.71
   },
   {
    "word": "में",
    "start": 3.35
   },
   {
    "word": "बाँटें।",
    "start": 3.57
   }
  ],
  "words": [
   {
    "word": "Classify",
    "start": 0.25
   },
   {
    "word": "each",
    "start": 0.25
   },
   {
    "word": "figure",
    "start": 0.53
   },
   {
    "word": "as",
    "start": 1.05
   },
   {
    "word": "a",
    "start": 1.6
   },
   {
    "word": "hexagon",
    "start": 1.6
   },
   {
    "word": "or",
    "start": 2.71
   },
   {
    "word": "a",
    "start": 3.35
   },
   {
    "word": "heptagon.",
    "start": 2.71
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/128.flac (c5Classify), 0.05-4.18 s"
 },
 {
  "text": "Well done! Hexagons have six sides and heptagons have seven sides.",
  "shown": "शाबाश! षट्भुज की 6 भुजाएँ होती हैं और सप्तभुज की 7 भुजाएँ।",
  "src": "assets/audio/lesson/hi/63_Well_done_Hexagons_have_six_sides_and_heptagons_have_seven_sid.mp3",
  "duration": 6.03,
  "spoken": [
   {
    "word": "शाबाश!",
    "start": 0.25
   },
   {
    "word": "षट्भुज",
    "start": 1.61
   },
   {
    "word": "की",
    "start": 2.2
   },
   {
    "word": "6",
    "start": 2.46
   },
   {
    "word": "भुजाएँ",
    "start": 2.72
   },
   {
    "word": "होती",
    "start": 3.2
   },
   {
    "word": "हैं",
    "start": 3.48
   },
   {
    "word": "और",
    "start": 3.96
   },
   {
    "word": "सप्तभुज",
    "start": 4.16
   },
   {
    "word": "की",
    "start": 4.76
   },
   {
    "word": "7",
    "start": 4.96
   },
   {
    "word": "भुजाएँ।",
    "start": 5.3
   }
  ],
  "words": [
   {
    "word": "Well",
    "start": 0.25
   },
   {
    "word": "done!",
    "start": 0.25
   },
   {
    "word": "Hexagons",
    "start": 1.61
   },
   {
    "word": "have",
    "start": 2.2
   },
   {
    "word": "six",
    "start": 2.46
   },
   {
    "word": "sides",
    "start": 2.72
   },
   {
    "word": "and",
    "start": 3.2
   },
   {
    "word": "heptagons",
    "start": 4.16
   },
   {
    "word": "have",
    "start": 4.16
   },
   {
    "word": "seven",
    "start": 4.96
   },
   {
    "word": "sides.",
    "start": 5.3
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/130.flac (c5WellDone), 0.04-6.07 s"
 },
 {
  "text": "Count the sides of the ones you placed wrong.",
  "shown": "जिन्हें आपने गलत जगह रखा, उनकी भुजाएँ गिनें।",
  "src": "assets/audio/lesson/hi/64_Count_the_sides_of_the_ones_you_placed_wrong.mp3",
  "duration": 3.86,
  "spoken": [
   {
    "word": "जिन्हें",
    "start": 0.25
   },
   {
    "word": "आपने",
    "start": 0.8
   },
   {
    "word": "गलत",
    "start": 1.1
   },
   {
    "word": "जगह",
    "start": 1.44
   },
   {
    "word": "रखा,",
    "start": 1.76
   },
   {
    "word": "उनकी",
    "start": 2.48
   },
   {
    "word": "भुजाएँ",
    "start": 2.82
   },
   {
    "word": "गिनें।",
    "start": 3.36
   }
  ],
  "words": [
   {
    "word": "Count",
    "start": 0.25
   },
   {
    "word": "the",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 2.82
   },
   {
    "word": "of",
    "start": 1.1
   },
   {
    "word": "the",
    "start": 1.44
   },
   {
    "word": "ones",
    "start": 1.76
   },
   {
    "word": "you",
    "start": 2.48
   },
   {
    "word": "placed",
    "start": 2.82
   },
   {
    "word": "wrong.",
    "start": 3.36
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/131.flac (c5CountWrong), 0.02-3.88 s"
 },
 {
  "text": "Six sides make a hexagon, seven make a heptagon.",
  "shown": "6 भुजाओं से षट्भुज बनता है, 7 से सप्तभुज।",
  "src": "assets/audio/lesson/hi/65_Six_sides_make_a_hexagon_seven_make_a_heptagon.mp3",
  "duration": 4.26,
  "spoken": [
   {
    "word": "6",
    "start": 0.25
   },
   {
    "word": "भुजाओं",
    "start": 0.51
   },
   {
    "word": "से",
    "start": 1.01
   },
   {
    "word": "षट्भुज",
    "start": 1.29
   },
   {
    "word": "बनता",
    "start": 1.81
   },
   {
    "word": "है,",
    "start": 2.21
   },
   {
    "word": "7",
    "start": 2.64
   },
   {
    "word": "से",
    "start": 3.03
   },
   {
    "word": "सप्तभुज।",
    "start": 3.29
   }
  ],
  "words": [
   {
    "word": "Six",
    "start": 0.25
   },
   {
    "word": "sides",
    "start": 0.51
   },
   {
    "word": "make",
    "start": 1.01
   },
   {
    "word": "a",
    "start": 1.29
   },
   {
    "word": "hexagon,",
    "start": 1.29
   },
   {
    "word": "seven",
    "start": 2.64
   },
   {
    "word": "make",
    "start": 2.64
   },
   {
    "word": "a",
    "start": 3.03
   },
   {
    "word": "heptagon.",
    "start": 3.29
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/132.flac (c5Rule), 0.05-4.31 s"
 },
 {
  "text": "Now you know everything about polygons. You are ready to help Momo.",
  "shown": "अब आप बहुभुज के बारे में सब कुछ जानते हैं। आप मोमो की मदद करने के लिए तैयार हैं।",
  "src": "assets/audio/lesson/hi/93_Now_you_know_everything_about_polygons_You_are_ready_to_help_Momo.mp3",
  "duration": 5.89,
  "spoken": [
   {
    "word": "अब",
    "start": 0.25
   },
   {
    "word": "आप",
    "start": 0.44
   },
   {
    "word": "बहुभुज",
    "start": 0.66
   },
   {
    "word": "के",
    "start": 1.22
   },
   {
    "word": "बारे",
    "start": 1.4
   },
   {
    "word": "में",
    "start": 1.66
   },
   {
    "word": "सब",
    "start": 1.9
   },
   {
    "word": "कुछ",
    "start": 2.19
   },
   {
    "word": "जानते",
    "start": 2.36
   },
   {
    "word": "हैं।",
    "start": 2.74
   },
   {
    "word": "आप",
    "start": 3.27
   },
   {
    "word": "मोमो",
    "start": 3.54
   },
   {
    "word": "की",
    "start": 3.9
   },
   {
    "word": "मदद",
    "start": 4.06
   },
   {
    "word": "करने",
    "start": 4.34
   },
   {
    "word": "के",
    "start": 4.66
   },
   {
    "word": "लिए",
    "start": 4.86
   },
   {
    "word": "तैयार",
    "start": 5.0
   },
   {
    "word": "हैं।",
    "start": 5.48
   }
  ],
  "words": [
   {
    "word": "Now",
    "start": 0.25
   },
   {
    "word": "you",
    "start": 0.44
   },
   {
    "word": "know",
    "start": 1.22
   },
   {
    "word": "everything",
    "start": 1.66
   },
   {
    "word": "about",
    "start": 1.9
   },
   {
    "word": "polygons.",
    "start": 0.66
   },
   {
    "word": "You",
    "start": 3.27
   },
   {
    "word": "are",
    "start": 3.54
   },
   {
    "word": "ready",
    "start": 4.06
   },
   {
    "word": "to",
    "start": 4.34
   },
   {
    "word": "help",
    "start": 4.86
   },
   {
    "word": "Momo.",
    "start": 5.0
   }
  ],
  "source": "Hindi take: assets/audio/source/hi/133.flac (endReady), 0.02-5.91 s"
 }
];
