/* Generated by tools/build-swiftee.cjs from source-art/swiftee-assets/swiftee-assets/atlas/swiftee.manifest.json — do not edit. */
window.SWIFTEE = {
 "fps": 20,
 "cell": 256,
 "pivot": {
  "x": 0.5,
  "y": 0.5,
  "note": "exact cell centre for every frame of every animation; matches engine defaults, so poses are interchangeable"
 },
 "baseline": 0.877,
 "states": {
  "talking": {
   "start": "talk_start",
   "loop": "talking",
   "stop": "talk_stop"
  },
  "waving": {
   "start": "wave_start",
   "loop": "waving",
   "stop": "wave_stop"
  },
  "happy": {
   "start": "happy_start",
   "loop": "happy",
   "stop": "happy_stop"
  },
  "confused": {
   "start": "confused_start",
   "loop": "confused",
   "stop": "confused_stop"
  },
  "curious": {
   "start": "curious_start",
   "loop": "curious",
   "stop": "curious_stop"
  },
  "celebrating": {
   "start": "celebrate_start",
   "loop": "celebrating",
   "stop": "celebrate_stop"
  },
  "proud": {
   "start": "proud_start",
   "loop": "proud",
   "stop": "proud_stop"
  },
  "surprised": {
   "start": "surprised_start",
   "loop": "surprised",
   "stop": "surprised_stop"
  },
  "relieved": {
   "start": "relieved_start",
   "loop": "relieved",
   "stop": "relieved_stop"
  },
  "daydreaming": {
   "start": "daydream_start",
   "loop": "daydreaming",
   "stop": "daydreaming_stop"
  },
  "puzzleing": {
   "start": "puzzle_start",
   "loop": "puzzleing",
   "stop": "puzzle_stop"
  }
 },
 "clips": {
  "talk_start": {
   "image": "assets/swiftee/swiftee_talk_start@1x.webp",
   "frames": 3,
   "cols": 2,
   "rows": 2,
   "pingpong": false,
   "exitsCell": false
  },
  "talking": {
   "image": "assets/swiftee/swiftee_talking@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "talk_stop": {
   "image": "assets/swiftee/swiftee_talk_stop@1x.webp",
   "frames": 5,
   "cols": 3,
   "rows": 2,
   "pingpong": false,
   "exitsCell": false
  },
  "wave_start": {
   "image": "assets/swiftee/swiftee_wave_start@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "waving": {
   "image": "assets/swiftee/swiftee_waving@1x.webp",
   "frames": 30,
   "cols": 6,
   "rows": 5,
   "pingpong": false,
   "exitsCell": false
  },
  "wave_stop": {
   "image": "assets/swiftee/swiftee_wave_stop@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "happy_start": {
   "image": "assets/swiftee/swiftee_happy_start@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "happy": {
   "image": "assets/swiftee/swiftee_happy@1x.webp",
   "frames": 40,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "happy_stop": {
   "image": "assets/swiftee/swiftee_happy_stop@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "confused_start": {
   "image": "assets/swiftee/swiftee_confused_start@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "confused": {
   "image": "assets/swiftee/swiftee_confused@1x.webp",
   "frames": 40,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "confused_stop": {
   "image": "assets/swiftee/swiftee_confused_stop@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "curious_start": {
   "image": "assets/swiftee/swiftee_curious_start@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "curious": {
   "image": "assets/swiftee/swiftee_curious@1x.webp",
   "frames": 33,
   "cols": 6,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "curious_stop": {
   "image": "assets/swiftee/swiftee_curious_stop@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "celebrate_start": {
   "image": "assets/swiftee/swiftee_celebrate_start@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "celebrating": {
   "image": "assets/swiftee/swiftee_celebrating@1x.webp",
   "frames": 50,
   "cols": 8,
   "rows": 7,
   "pingpong": false,
   "exitsCell": false
  },
  "celebrate_stop": {
   "image": "assets/swiftee/swiftee_celebrate_stop@1x.webp",
   "frames": 10,
   "cols": 4,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "proud_start": {
   "image": "assets/swiftee/swiftee_proud_start@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "proud": {
   "image": "assets/swiftee/swiftee_proud@1x.webp",
   "frames": 40,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "proud_stop": {
   "image": "assets/swiftee/swiftee_proud_stop@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "surprised_start": {
   "image": "assets/swiftee/swiftee_surprised_start@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "surprised": {
   "image": "assets/swiftee/swiftee_surprised@1x.webp",
   "frames": 47,
   "cols": 7,
   "rows": 7,
   "pingpong": true,
   "exitsCell": false
  },
  "surprised_stop": {
   "image": "assets/swiftee/swiftee_surprised_stop@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "relieved_start": {
   "image": "assets/swiftee/swiftee_relieved_start@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "relieved": {
   "image": "assets/swiftee/swiftee_relieved@1x.webp",
   "frames": 45,
   "cols": 7,
   "rows": 7,
   "pingpong": false,
   "exitsCell": false
  },
  "relieved_stop": {
   "image": "assets/swiftee/swiftee_relieved_stop@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "daydream_start": {
   "image": "assets/swiftee/swiftee_daydream_start@1x.webp",
   "frames": 8,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "daydreaming": {
   "image": "assets/swiftee/swiftee_daydreaming@1x.webp",
   "frames": 40,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "daydreaming_stop": {
   "image": "assets/swiftee/swiftee_daydreaming_stop@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "puzzle_start": {
   "image": "assets/swiftee/swiftee_puzzle_start@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "puzzleing": {
   "image": "assets/swiftee/swiftee_puzzleing@1x.webp",
   "frames": 37,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "puzzle_stop": {
   "image": "assets/swiftee/swiftee_puzzle_stop@1x.webp",
   "frames": 7,
   "cols": 3,
   "rows": 3,
   "pingpong": false,
   "exitsCell": false
  },
  "blinking": {
   "image": "assets/swiftee/swiftee_blinking@1x.webp",
   "frames": 40,
   "cols": 7,
   "rows": 6,
   "pingpong": false,
   "exitsCell": false
  },
  "flapping": {
   "image": "assets/swiftee/swiftee_flapping@1x.webp",
   "frames": 27,
   "cols": 6,
   "rows": 5,
   "pingpong": false,
   "exitsCell": false
  },
  "reset": {
   "image": "assets/swiftee/swiftee_reset@1x.webp",
   "frames": 3,
   "cols": 2,
   "rows": 2,
   "pingpong": false,
   "exitsCell": false
  }
 }
};
