#!/usr/bin/env node
/* Writes src/i18n/locales.js, the words of src/i18n/locales.json as one classic script:

     window.POLYGON_LOCALES = { ... };

   A page opened straight off the disk (file://) cannot fetch() locales.json -- a browser gives
   such a page no origin and refuses -- so src/i18n/i18n.js loads this script instead there.
   Over http:// the JSON is fetched as before and this file is never asked for; the deployment
   leaves it out (.vercelignore).

     node tools/i18n/build-locales.cjs           write it
     node tools/i18n/build-locales.cjs --check   write nothing; exit 1 if it is out of date */
const fs = require('fs');
const path = require('path');

const DIR = path.resolve(__dirname, '..', '..', 'src', 'i18n');
const SRC = path.join(DIR, 'locales.json');
const OUT = path.join(DIR, 'locales.js');

const words = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const text = '/* Generated by tools/i18n/build-locales.cjs from locales.json -- do not edit. The words as a\n' +
  '   script, for a page opened off the disk (file://), where fetch() is refused; see i18n.js. */\n' +
  'window.POLYGON_LOCALES = ' + JSON.stringify(words) + ';\n';

const check = process.argv.includes('--check');
const same = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === text;
if (check) {
  if (!same) { console.error('src/i18n/locales.js is out of date: run node tools/i18n/build-locales.cjs'); process.exit(1); }
  console.log('src/i18n/locales.js is up to date');
} else if (same) console.log('src/i18n/locales.js is up to date');
else { fs.writeFileSync(OUT, text); console.log('wrote src/i18n/locales.js (' + Math.round(text.length / 1024) + ' KB)'); }
