/* Builds assets/swiftee/ from the Swiftee character pack.
     node tools/build-swiftee.cjs
   Copies only the @1x sheets the lesson's guide actually plays and writes
   src/lesson/swiftee-sheets.js, a window.SWIFTEE constants file generated from
   atlas/swiftee.manifest.json — frame counts, grids, fps and the start/loop/stop
   triads all come from the manifest, never from hand-typed numbers. Re-run it
   whenever SHIP changes or the pack is rebuilt. source-art/swiftee-assets/ itself stays
   out of the deploy (.vercelignore); the lesson only loads what this emits. */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const PACK = path.join(ROOT, 'source-art', 'swiftee-assets', 'swiftee-assets');
const OUT = path.join(ROOT, 'assets', 'swiftee');
const TABLE = path.join(ROOT, 'src', 'lesson', 'swiftee-sheets.js');
const SCALE = '1x';
/* States (full start → loop → stop triads) and standalone clips the guide uses. */
const SHIP = {
  states: ['talking', 'waving', 'happy', 'confused', 'curious', 'celebrating', 'proud',
           'surprised', 'relieved', 'daydreaming', 'puzzleing'],
  clips: ['blinking', 'flapping', 'reset']
};
const manifest = JSON.parse(fs.readFileSync(path.join(PACK, 'atlas', 'swiftee.manifest.json'), 'utf8'));
const sheets = manifest.scales[SCALE].sheets;
fs.mkdirSync(OUT, { recursive: true });
const clips = {}, states = {};
function ship(name) {
  const s = sheets[name];
  if (!s) throw new Error('manifest has no ' + SCALE + ' sheet for "' + name + '"');
  if (s.pages !== 1) throw new Error(name + ' is paged; the lesson player expects one page');
  const file = path.basename(s.image);
  fs.copyFileSync(path.join(PACK, s.image), path.join(OUT, file));
  const anim = manifest.animations[name] || {};
  clips[name] = { image: 'assets/swiftee/' + file, frames: s.frames, cols: s.cols, rows: s.rows,
    pingpong: !!anim.pingpong, exitsCell: manifest.exitsCell.includes(name) };
}
SHIP.states.forEach(st => {
  const t = manifest.states[st];
  if (!t) throw new Error('manifest has no state "' + st + '"');
  states[st] = { start: t.start, loop: t.loop, stop: t.stop };
  t.play.forEach(ship);
});
SHIP.clips.forEach(ship);
const data = {
  fps: manifest.fps, cell: manifest.cell[SCALE], pivot: manifest.pivot,
  baseline: manifest.baselineY.normalized, states, clips
};
fs.writeFileSync(TABLE,
  '/* Generated by tools/build-swiftee.cjs from source-art/swiftee-assets/swiftee-assets/atlas/swiftee.manifest.json — do not edit. */\n' +
  'window.SWIFTEE = ' + JSON.stringify(data, null, 1) + ';\n');
const bytes = fs.readdirSync(OUT).reduce((n, f) => n + fs.statSync(path.join(OUT, f)).size, 0);
console.log('wrote ' + Object.keys(clips).length + ' sheets to assets/swiftee (' + (bytes / 1024).toFixed(0) + ' KB) and src/lesson/swiftee-sheets.js');
